### ISSUE TITLE
Command line completion with CTRL-D and TAB

### ISSUE THREAD

**Issue by erf** [martanne/vis#100]
Show a list of commands with CTRL-D
Command completion with TAB

**Comment by martanne** [comment]
As stated elsewhere I would like to avoid it, if possible. The current approach is to have only few options/commands with aliases/unique prefixes such that completion is not needed. For file related tab completion the integration with `vis-open`/`slmenu` could probably be improved a bit.

This issue is a duplicate of #25 and #70.

**Comment by erf** [comment]
What do you think about using <code>CTRL-j</code> and <code>CTRL-k</code> as aliases of left and right arrow when selecting file with slmenu?

**Comment by martanne** [comment]
Yes this might be an option. However this can't be changed without forking slmenu which then raises the question whether vis should ship its own menu.

Also <kbd>Tab</kbd> in prompt mode could launch vis-open with the current prompt content followed by an asterisk as file pattern. That is `:edit vis`<kbd>Tab</kbd> would be expanded to something  like `ls -1 vis* 2>/dev/null | slmenu vis` where the argument to slmenu indicates the default/starting prompt value.
