### ISSUE TITLE
vis future?

### ISSUE THREAD

**Issue by Sneethe** [martanne/vis#1001]
Last commit was over a year ago.

**Comment by realwhz** [comment]
I am not sure if this discussion is a bit off-topic.  I started using vis since 2018.  It is never my major editor for programming but always part of my workflow.  I use vis whenever I have bunch of tedious and repetitive changes to make.  Its Sam regex based selection is so convenient.  For example, I can easily step by step build the selection and make the change.  There are more and more plugins developed for vis those days.  I seldom install any as I want to keep vis light and sharp.

**Comment by erf** [comment]
There was a similar issue here #748 some time back . I guess the future is in the hands of the author or if anybody else would like to create a fork and step up to the plate .  I really enjoy **vis** as a light weight vim alternative and its Sam regex based selection and Lua API is great . I think it is an awesome alternative / competitor to other terminal based text editors like vim, nvim, kakoune etc. without the bloat of legacy code . What i would like to see next is the server / client architecture, or non-blocking IO as implemented here #675 which made it possible to implement the Language Server Protocol (LSP) in the issue here #853 . Another exciting feature is Tree-sitter discussed here  #668 for better built in lexers. There is also just the general maintenance - which takes a lot of time and the author does all the work pro bono (!) - so we can't really expect anything . Although some words regarding the status would be nice . I don't have much c skills, but have been enjoying playing around with the Lua API . I think **vis** will still be relevant in years to come <3

**Comment by acidrums4** [comment]
I've been using vis as my main/only 'development' editor (alongside KDE's kwrite, which I use as a scratchpad) for a relative short time (2+ years?) and thus following the repo despite me not being a developer by any means. Though personally I'd disagree with the 'benevolent dictador for life' government model, I won't like vis to be forked - it'll mean a change in its direction and vision, and who knows, in this days people like things to be rewritten in Rust...

Despite at some points it seems not to, its main developer has a clear structure of what he's done and what he wants of it, which actually is one of the greatest perks (if not the greatest) of vis. But certainly the development process has slowed a lot since a few years. The server/client architecture discussion, which I too agree is what I'd love to have next, has been around and unresolved for several years. Even the discussion about the 'vis' name seems halted (#338).

One can only hope its main developer is doing fine and just taking some rest as the last time, but meanwhile it'd be great people could be submitting pull requests, giving ideas and reporting bugs, and even for an development illiterate like me, spreading the word of it so people can discover it and get involved.

**Comment by deepcube** [comment]
I have been in contact with martanne recently. He has agreed to give a few of us access to the repos. We are going to start triaging tickets and merging changes. It will be a very slow, careful process. We don't want to make things worse, and we don't have the intricate knowledge of the internals that martanne had. Please do be patient as we learn the ropes.

**Comment by skogshjort** [comment]
@deepcube That is great news! I've used vis as my main editor for some years and enjoy it immensely. Take it at your own pace, there is no rush really. It is a very usable lightweight editor in its current state. I was just swinging by to add an issue about undo history, but I'm glad you're relieving some weight off of martanne's shoulders :) Also, @martanne thank you for such an inspiring tool! Hugs

**Comment by ninewise** [comment]
Pushed a commit to change the discussion channel to #vis-editor on libera. I'll close this issue as the first step in triaging - since I guess that commit answers the 'vis future?' question.

**Comment by erf** [comment]
@ninewise How about creating a Discord server for vis? I saw SerenityOS had great success building a community with it after switching from IRC. You can create different channels for various topics and persist messages / users

**Comment by deepcube** [comment]
@erf I'm not necessarily opposed to the idea, but I think for now we want to focus on minimal changes as we get up and running, I want to avoid unnecessary churn. We already have IRC, mailing list, sourcehut tickets, and github issues. I don't want to add/remove anything yet just to make sure any existing users know where to look. Once things are running smoothly I'm open to discussing other possibilities.

**Comment by Sneethe** [comment]
I'm very happy reading this to see there are still people passionate about this great little editor. :)

**Comment by mcepl** [comment]
* [ ] #992 :+1: trivial
  * [ ] #989 :+1: trivial
  * [ ] #675 another review (what about #988?)
  * [ ] #963 :+1:
  * [ ] #984 :-1:
  * [ ] #983 :+1:
  * [ ] #986 :+1: trivial
  * [ ] #957 comment
  * [ ] #944 not sure to think about it: I don't understand enough to say whetehr it is correct, but OTOH it shouldn't hurt, should it?
  * [ ] #933 ditto
  * [ ] #881 looks tempting, but I don't know whether it is correct, will test
  * [ ] #769 :+1: looks trivial
