### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by erf** [martanne/vis#101]
The new LUA addition looks exiting. I tried to install the third party libraries manually, but i think i screwed something up, because i can't see syntax highlighting. This is probably due to LUA or LPEG, but i did not get any errors. Anyone successful at building for OSX ?

**Comment by martanne** [comment]
Your subject refers to a build issue, but then you state that you do not get any errors (hence the build was successful)? Did you do `make install` or set `VIS_PATH=. ./vis`?

**Comment by erf** [comment]
I ran make and it built without errors but I guess i was making the assumption that some third party library was not working correctly since syntax highlighting was not showing, and that the build process could be improved upon for OSX. But i guess this could be another issue as well. Feel free to rename it.

**Comment by erf** [comment]
I did do <code>make install</code>

**Comment by martanne** [comment]
Run `VIS_PATH=. ./vis` from the build directory. If it does not work, use the Mac OS X equivalent of `strace(1)` and check what files it tries to open.

**Comment by erf** [comment]
I ran <code>VIS_PATH=. ./vis</code> but i get the following warning:
<pre>Warning: failed to load theme `default-256' set $VIS_PATH</pre>
I believe it's because lpeg is not properly installed, and i'm not sure how to install it. The <code>make local</code> does not work.

**Comment by martanne** [comment]
I assume you have built lpeg using `make macosx`? After that you must place the resulting `lpeg.so` file somewhere in the lua package path. Start the interactive lua interpreter and execute: `print(package.cpath)`.

Anyway, except for the non-existing error reporting this is not a vis issue ...

**Comment by erf** [comment]
Got it working by putting the lpeg.so in the right place.

I'm surely lacking some know-how in the linux / unix world, but automating the install process for vis on osx would be sweet.

**Comment by twe4ked** [comment]
@erf Once there is a version we can look at getting it on homebrew.

**Comment by erf** [comment]
@twe4ked Yes let's do that.

**Comment by martanne** [comment]
@twe4ked did you ever start packaging for homebrew? This would at least partially cover #162.

**Comment by twe4ked** [comment]
I had a quick look into it over the weekend but I ran out of time. I'll try get around to it soon.

**Comment by martanne** [comment]
Thanks, looking forward to it! I had a quick look at the package repository, both libtermkey and Lua 5.2 are already packaged and should not cause any problems. LPeg might be a bit more tricky because homebrew seems to have some issues with Lua dependency management? The [sile formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sile.rb#L21) refers to it in some way ...

**Comment by twe4ked** [comment]
I've [opened a PR](https://github.com/Homebrew/homebrew/pull/50569) to add vis to homebrew.

**Comment by twe4ked** [comment]
There were a few issues with the PR that I've fixed up. [Here's what it looks like](https://gist.github.com/twe4ked/2b06c98bf1604e9b487cbebbcdf08619) to install. The lua dependencies and the `vis(1)` conflict make things a bit more difficult.

**Comment by martanne** [comment]
Thanks! So the installation procedure would be:

```
$ brew install lua && luarocks-5.2 install lpeg
$ brew install vis && brew link --force vis
```

Better than compiling from source I guess. Not sure why homebrew does not manage to properly handle Lua dependencies.

As for the name clash, I was aware of it, but at the time thought it would still be a fitting project name. Partly because of [cat -v considered harmful](http://harmful.cat-v.org/cat-v/) which is the reason the original `vis` command exists. After all a goal of vis (the editor) is to handle arbitrary files and visually display them ...

The other main reason is that the computer science student organization at my university is also called vis, and they "sponsored" development with their free coffee service. Because the starting point for the whole project was a university course covering Project Oberon this reference seemed appropriate.

**Comment by iyee** [comment]
@martanne How did you make `brew install vis` working? It's not in the homebrew repo and there's not a *martanne/homebrew-vis* repo for `brew tap`.
