### ISSUE TITLE
Implement = to indent content ?

### ISSUE THREAD

**Issue by erf** [martanne/vis#112]
Implement = to indent content ?

**Comment by martanne** [comment]
Language specific indention should probably be taken care of by external tools, see also the discussion in [this pull request](https://github.com/martanne/vis/pull/33).

What probably could be done is to apply the indention of the first line to all remaining ones (similarly to what the current auto indentation code does). Not sure if this is useful though, I personally hardly ever use `=`.

**Comment by erf** [comment]
Yes maybe you could reuse the auto indentation code, by stepping through lines. `=` is an operation though so you should probably be able to use it with a line number or G. 
I find it useful sometimes when i remove some outer scope of a function and want to reindent.

**Comment by erf** [comment]
Talking about external tools, have you considered libuv for IO ?

**Comment by martanne** [comment]
As I outlined above, in this simple form `=` would copy the indention of the first line from the covered range. Hence something like `gg=G` won't work because it will unindent the whole file (assuming there is no indention on the very first line). This behaviour doesn't seem useful and is the reason why it has not been implemented so far.

Regarding libuv, yes it would probably be the "correct" thing to do, especially if we ever want to support Microsoft Windows. However I'm a bit reluctant, vis started out as really simple tool (probably still is depending on your metric) but has since introduced dependencies on libtermkey, lua, lpeg etc. each of those can be justified, but still ...

**Comment by martanne** [comment]
`=` is now implemented using `fmt(1)` it should be obvious how to change this to your favorite external tool.

**Comment by erf** [comment]
Great! I got it working with (Uglifyjs)[https://github.com/mishoo/UglifyJS2] by changing the `operator_filter` in `main.c`, is there an other way to configure this?
