### ISSUE TITLE
Theming is sometimes partially applied or ignored

### ISSUE THREAD

**Issue by lobre** [martanne/vis#1151]
It seems I cannot define the foreground color of a visual selection.

```
lexers.STYLE_SELECTION = 'fore:yellow'
```

This above does not work. Not sure if the problem is in this repo or in https://github.com/orbitalquark/scintillua/

**Comment by lobre** [comment]
Thank you for the fix. It also seems to me that the "matching pair" is colored using the style of `STYLE_SELECTION`. However, the foreground color is not applied either, despite your above patch.

**Comment by rnpnr** [comment]
Fixed again! A lot of that code looks like it could do with a bit of a refactoring. Most of it is just duplicated in multiple places.

**Comment by lobre** [comment]
Thank you a lot for those quick fixes!

I am currently building a simple 16-color theme so I discover those small issues during the process.

Allow me to report another small one. Here is an extract of the theme:

```
lexers.STYLE_IDENTIFIER = 'fore:white'
lexers.STYLE_OPERATOR = 'fore:white' -- this one includes parenthesis
lexers.STYLE_STRING = 'fore:yellow'
lexers.STYLE_SELECTION = 'back:white,fore:black'
```

And let's take this example of code:

![vis_code_noselect](https://github.com/martanne/vis/assets/3764103/80d0d5d6-7b0d-44cc-837a-ec30ddc840c9)

You can see that labels `layoutDatetime`, `layoutDate` and `layoutTime` match `STYLE_IDENTIFIER`. Then the quoted dates match `STYLE_STRING` while the parenthesis match `STYLE_OPERATOR`.

But if I go into visual selection, the `fore:black` is not applied on labels and parenthesis, while it applies to the strings. See in action:

![vis_code_select](https://github.com/martanne/vis/assets/3764103/ed0eecd8-dc62-4e9a-9322-346501a42d42)

I don't know if this is as trivial as the others.

**Comment by rnpnr** [comment]
> Thank you a lot for those quick fixes!

Actually I think I introduced a different bug. Now if you don't set the foreground color for `STYLE_SELECTION` it changes everything to the terminal foreground color instead of keeping the underlying foreground color.

> In my opinion, the selection should always override what is on the other styles.

I agree. If `STYLE_SELECTION` has anything set and you make a selection it should apply. Otherwise it should just keep the underlying style.

> Also, it seems putting `reverse` for the cursor does not work.

I've also noticed that the attributes (`reverse`, `bold`, `italic`, `blink`) don't always  get applied.

All in all that code is very crusty. It needs to be broken out into a separate "apply style" function so that fixes can be made in one place instead of all over.
