### ISSUE TITLE
mixed splits

### ISSUE THREAD

**Issue by wthurein** [martanne/vis#119]
With current head on OS X 10.11:
Mixed splits don't seem to be supported. A :split followed by a :vsplit will result in three vertical splits; likewise, a :vsplit followed by a :split will result in three horizontal splits.

**Comment by martanne** [comment]
This is intentional (see also first point of the [non goals section](https://github.com/martanne/vis#non-goals)). The long term plan is to adapt a client/server model where each window would be an isolated process. This way your favorite window manager / terminal multiplexer can take care of window placement.
