### ISSUE TITLE
[Feature Request]: Sleeping cursors (multiple cursors)

### ISSUE THREAD

**Issue by rsmirnov90** [martanne/vis#1211]
### What feature would you like to see?

Hello! Long-time vis user, first-time poster here.

I’ve been exploring the whole "multiple cursors" concept for a while now, because a lot of editors handle it in ways that feel... clunky. Most implementations seem tailored to the developer's specific workflow, which doesn't always translate well for everyone else. And since multiple cursors are a relatively new thing (in terms of UI/UX practices), many editors seem to bolt it on without much thought for clean integration.

That got me thinking: what’s the most minimal, flexible, core approach we could use as a foundation for any workflow? Kind of like how vi/vis command modes or regex underpin so much of what we do in text manipulation?

Then I came across MLE (https://github.com/adsr/mle), which has the cleanest solution I’ve seen: you just drop a "sleeping cursor" wherever you want, and activate them whenever needed. Simple, but it opens up endless workflow possibilities.

I think this aligns perfectly with vis’s design philosophy, but I’d love to hear your thoughts:

1) How do you feel about this conceptually?

2) Does it fit within vis’s philosophy in practice?

3) Would you be open to something like this being added?

If so, I’d be excited to help bring it to life.

**Comment by mcepl** [comment]
1. If you want to use other text editor, use it.
2. If you want us to provide with some new feature, please, sit down and specify it as precisely as you are able to. If you say, “do it like them”, it means your time is too precious to sit down and do the specification, and we should do it instead of you. We should sit down, install some editor we don’t care about, study it and then divine what you meant by saying “do it like them”. That is not like the FLOSS world works. You should be paying others for doing work for you by doing as much as you are able.
3. Issue tracker is for issues, with specified problem, and suggested solution, not for a free flow discussion. Please, send an email message to the email list https://lists.sr.ht/~martanne/devel

Thank you.

**Comment by rsmirnov90** [comment]
1. Thank you for your permission. I have not considered this idea.

2. There is **nowhere** I said that I wanted you to provide anyone with any kind of feature. The way "the FLOSS world works" is on any project there is one (or more) project leaders who have a certain vision for the project. When somebody else (from outside) wants to add a large new feature, usually it is polite to ask first if it fits with the project vision of the leaders and the best way to do it, and if they have other ideas. I asked **three** questions in my post, all of them about the project leadership's opinion and view on this kind of feature, and if it fits with the editor philosophy, because I wanted to add it. 

3. This is the first time I hear about the mailing list. The project pages do not mention anythign about it, and the Github issue tracker had a tag for "feature request" and other feature discussions open. (Although this was not a feature "request", but an attempt to discuss an idea).

Have a good day.

**Comment by fischerling** [comment]
Don't get discouraged by @mcepl! They usually are very harsh and strict about how the vis project has to work.

If you want to explore some different UX and feel that vis is the right place for your work, definitely give it a shot.

I personally can not imagine how a feature like sleeping cursors would improve the way I use vis, but I am curious.

However, do not expect bigger changes to get merged easily.

**Comment by rsmirnov90** [comment]
@fischerling Thank you, I will give it a shot! 

The idea behind sleeping cursors is to mainly provide a "baseline" way for having multiple selections. 

So for example, to take a step back and use a simpler case, as experienced vi/vim/vis users we usually do not use the hjkl or arrow key motions anymore; instead, the majority of the time we navigate based on gestures (and everyone has their own preferences with this; i.e. some people mentally calculate how many words ahead or behind they need to jump, others use search, others go by fixed or relative line numbers, etc). However, at the end of the day, the most basic motions in any text editor are still the directional keys (h/j/k/l or up/down/left/right). All motions above this are higher-level constructs, but at the end of the day -- we are still moving the cursor up, down, left, or right.

With multiple cursors, I also see many editors (including vis) implement high-level motions and actions, but oftentimes there is no "basic"/"primitive" action to serve as a starting point. A command to "place a cursor here in this arbitrary location". Such a functionality could serve as a base action for many different multiple-cursor workflows, but I think it fits with the philosophy of vis (and vi in general) of providing very flexible building blocks from which a user can then build a workflow.

So I think it would be a good experiment to try this in vis, because at least after my own > 1 year of using it I think it fits the model pretty well.

**Comment by mcepl** [comment]
> There is **nowhere** I said that I wanted you to provide anyone with any kind of feature.

I will not interrupt the conversation with @fischerling, but let me just note that this ticket is called “[Feature Request]”. Just saying.

And yes, there is an obvious bug, that we don’t have mentioned the email list in README. I suggest fix in https://lists.sr.ht/~martanne/devel/patches/55613

**Comment by rsmirnov90** [comment]
@mcepl Completely understood! I apologize too for getting overly defensive so quickly, and I totally understand how frustrating it is when people start demanding random features in an open source project. 

Just a quick note, the reason it says "Feature Request" is because when opening a New Issue on Github there are only two selectable options there -- "Bug Report" and "Feature Request" (there is also a button for the mailing list which I see now, but as it is an external link I guess I didn't consider that it would be the right place).

I will reach out again when I have the beginnings of a working concept (this time, on the mailing list! 😁)

**Comment by deepcube** [comment]
Quoting Russ (2024-10-23 22:37:16)
> The idea behind sleeping cursors is to mainly provide a "baseline" way for having multiple selections.
>
>
> A command to "place a cursor here in this arbitrary location". Such
> a functionality could serve as a base action for many different
> multiple-cursor workflows, but I think it fits with the philosophy
> of vis (and vi in general) of providing very flexible building blocks
> from which a user can then build a workflow.
>
> So I think it would be a good experiment to try this in vis, because
> at least after my own > 1 year of using it I think it fits the model
> pretty well.

The basics for this already exist, and you could probably add simple
"shortcuts" to make it more convenient.  An example workflow to do this
now would be:

m	mark the current selection using the default mark
...	move to the next location you want a cursor
|	union the selection in the default mark with the current selection
m	mark the current selection using the default mark
esc	dispose all but the primary selection
...	move to the next location you want a cursor
|	union the selection in the default mark with the current selection
m	mark the current selection using the default mark
esc	dispose all but the primary selection
...
Repeat as necessary.

You then end with | to have all the selections you want, or if you've
moved off then realized you have no more places to put a cursor you do
M to recall that default mark.

All of these can also be done with named marks instead of the default
mark if you wish (e.g. 'am 'a| .... 'am 'a| ...).

It seems like the missing primitive is "add current selection to given
mark then return to current selection."

hmmm.... Ok this seemed useful enough and easy enough that I decided to
hack something together.  Give this patch a go:

From dc3a459d924017cdd413c0db6f6f6fe36cae5f9e Mon Sep 17 00:00:00 2001
From: Evan Gates ***@***.***>
Date: Fri, 25 Oct 2024 17:38:35 -0600
Subject: [PATCH] selections: sleeping cursors

Add selections_sleep, assigned to ! by default, to union the current
selection with a mark, save the mark, then return to the original current
selection.  This makes it easier to navigate and "drop sleeping cursors"
in multiple places then recall them to edit in multiples places.
---
 config.def.h |  1 +
 main.c       | 19 +++++++++++++++++++
 2 files changed, 20 insertions(+)

diff --git a/config.def.h b/config.def.h
index 54be734..d51f4c7 100644
--- a/config.def.h
+++ b/config.def.h
@@ -130,6 +130,7 @@ static const KeyBinding bindings_selections[] = {
 	{ "m",                  ACTION(SELECTIONS_SAVE)                     },
 	{ "M",                  ACTION(SELECTIONS_RESTORE)                  },
 	{ "|",                  ACTION(SELECTIONS_UNION)                    },
+	{ "!",                  ACTION(SELECTIONS_SLEEP)                    },
 	{ "&",                  ACTION(SELECTIONS_INTERSECT)                },
 	{ "~",                  ACTION(SELECTIONS_COMPLEMENT)               },
 	{ "\\",                 ACTION(SELECTIONS_MINUS)                    },
diff --git a/main.c b/main.c
index 8aa31c6..524afb2 100644
--- a/main.c
+++ b/main.c
@@ -80,6 +80,8 @@ static const char *selections_save(Vis*, const char
*keys, const Arg *arg);
 static const char *selections_restore(Vis*, const char *keys, const Arg *arg);
 /* union selections from mark */
 static const char *selections_union(Vis*, const char *keys, const Arg *arg);
+/* union selections from mark */
+static const char *selections_sleep(Vis*, const char *keys, const Arg *arg);
 /* intersect selections from mark */
 static const char *selections_intersect(Vis*, const char *keys, const
Arg *arg);
 /* perform complement of current active selections */
@@ -282,6 +284,7 @@ enum {
 	VIS_ACTION_SELECTIONS_SAVE,
 	VIS_ACTION_SELECTIONS_RESTORE,
 	VIS_ACTION_SELECTIONS_UNION,
+	VIS_ACTION_SELECTIONS_SLEEP,
 	VIS_ACTION_SELECTIONS_INTERSECT,
 	VIS_ACTION_SELECTIONS_COMPLEMENT,
 	VIS_ACTION_SELECTIONS_MINUS,
@@ -1032,6 +1035,11 @@ static const KeyAction vis_action[] = {
 		VIS_HELP("Add selections from mark")
 		selections_union
 	},
+	[VIS_ACTION_SELECTIONS_SLEEP] = {
+		"vis-selections-sleep",
+		VIS_HELP("Add selections from mark")
+		selections_sleep
+	},
 	[VIS_ACTION_SELECTIONS_INTERSECT] = {
 		"vis-selections-intersect",
 		VIS_HELP("Intersect with selections from mark")
@@ -1602,6 +1610,17 @@ static void selections_set(Vis *vis, View
*view, Array *sel) {
 		view_selections_clear_all(view);
 }

+static const char *selections_sleep(Vis *vis, const char *keys, const
Arg *arg) {
+	View *view = vis_view(vis);
+	Array sel = view_selections_get_all(view);
+	selections_union(vis, keys, arg);
+	selections_save(vis, keys, arg);
+	selections_clear(vis, keys, arg);
+	selections_set(vis, view, &sel);
+	array_release(&sel);
+	return keys;
+}
+
 static const char *selections_save(Vis *vis, const char *keys, const
Arg *arg) {
 	Win *win = vis_window(vis);
 	View *view = vis_view(vis);
-- 
2.46.0

**Comment by rsmirnov90** [comment]
@deepcube This is brilliant, thank you so much for taking the time!! Seems like a perfect starting point for me; I will look deeper into this today.

**Comment by mcepl** [comment]
Entering patch as plain text to a comment leads to its corruption. Reapplied as https://git.cepl.eu/cgit/vis/vis/commit/?h=sleeping_cursors&id=bc0877b9785dea8a37deb35c7c0110d3b548a313

**Comment by deepcube** [comment]
Quoting Matěj Cepl (2024-10-30 09:58:57)
> Entering patch as plain text to a comment
> leads to its corruption. Reapplied as
> https://git.cepl.eu/cgit/vis/vis/commit/?h=sleeping_cursors&id=bc0877b9785dea8a37deb35c7c0110d3b548a313

Sigh, of course it does.  One more reason to prefer the mailing list.
Thanks for making it usable.
