### ISSUE TITLE
ACTION(REDRAW) (bound to C-l) doesn't work.

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#126]
```diff
diff --git a/ui-curses.c b/ui-curses.c
index 58c1298..151cee9 100644
--- a/ui-curses.c
+++ b/ui-curses.c
@@ -752,7 +752,7 @@ static void ui_arrange(Ui *ui, enum UiLayout layout) {
 
 static void ui_draw(Ui *ui) {
 	UiCurses *uic = (UiCurses*)ui;
-	erase();
+	clear();
 	ui_arrange(ui, uic->layout);
 
 	for (UiCursesWin *win = uic->windows; win; win = win->next)

```

**Comment by martanne** [comment]
Thanks for the report! This should hopefully be fixed by 8572b583712abc80ee2a791b0e66d09cbfc28721? Calling clear upon every screen change is probably not what we want, that would essentially disable the double buffering performed by the curses library. Because vis itself does not try to optimize ui updates, this could cause lots of unecessary terminal output.
