### ISSUE TITLE
How to substitute with newlines?

### ISSUE THREAD

**Issue by khaaan** [martanne/vis#131]
How do I substitute something with newlines in vis?

In vim, I would do `:s/x/\r/g`    or `:s/x/<ctrl-v><enter>/g`    (where `<ctrl-v>` represents pressing ctrl+v and `<enter>` represents pressing the enter/return key). But neither of those work in vis.

**Comment by martanne** [comment]
vis currently uses `sed(1)` to implement the `:substitute` command. 

That is if you are on a system with GNU sed in `$PATH` something like `:s/x/\n/g` should work. Unfortunately POSIX does not seem to specify escape characters in the replacement string and the `:`-command prompt does not support multiline entries (something which would also be fixed by #70). Hence if you are on a system without support for `\n` in sed you might want to use perl (or any other scripting language of your choice) `:%!perl -pe 's/,/\n/g'`.

With the latest commits (enhancing <kbd>Ctrl-v</kbd>) you can now also do: `:s/x/\`<kbd>Ctrl-v</kbd><kbd>Enter</kbd>`/g` notice the additional `\` before <kbd>Ctrl-v</kbd> which constructs the following sed command:

    s/x/\
    /g

**Comment by khaaan** [comment]
Thanks. I installed GNU sed and now the \n substitution works great, so my original problem is solved.

I also tried <kbd>\\</kbd> <kbd>Ctrl-v</kbd> as you suggested (after running `git pull` then re-compiling `vis`), but I get this error right after I press <kbd>Enter</kbd>:
```
Command failed: sed: -e expression #1, char 10: unterminated `s' command
```

Here's what the vis command line looks like right before I press <kbd>Enter</kbd>:
```
:s/x/\<C-v> 
```

**Comment by martanne** [comment]
Try `rm config.h && make`. For now the default key bindings are stored in `config.def.h` (changed by the latest commit) with local modifications possible in `config.h`. Hence you will have to manually merge the two files when the former changes.

**Comment by khaaan** [comment]
That worked. Thanks.
