### ISSUE TITLE
OOM behavior

### ISSUE THREAD

**Issue by Pyrohh** [martanne/vis#139]
Currently, it seems like vis tries to handle running out of memory gracefully, in that it doesn't immediately an exit routine upon malloc(3) and friends returning NULL. I'm not sure this is worth it, since:
- It introduces the possibility of unchecked allocations (I noticed a few when looking call sites)
- It complicates error handling; I might be missing something, but I haven't noticed any instances of allocation error handling where the user has any idea what's going on besides implicitly, in that things stop working with no error message.

For the reasons mentioned above, and since running out of memory is probably not going to be of much concern to most users, I propose the usage of wrapper functions which exit if allocation fails. Here's a commit that does just that: https://github.com/Pyrohh/vis/commit/69482f206dbeeb0a3e5b07a6599c7c647f7bb58f

The exit routine is sub-par as it uses `<err.h>` functions (which isn't available everywhere) and doesn't call `endwin()` upon error, which looks ugly. In any case, it should get the point across regarding simpler error handling (i.e., none).

**Comment by martanne** [comment]
NAK.

I consider the text editor a core system component which should handle resource exhaustion gracefully. Large parts of the editor are written in a library like fashion which could be reused elsewhere, hence simply terminating upon failure is a unacceptable.

Unchecked allocation (leading to NULL pointer dereferences etc) are considered a bug and should be fixed. In the case of an editor the user actually has the possibility to react to memory pressure by for example closing large files.

Yet more advanced (and admittedly complex) the editor could try to release unused resources e.g. by discarding old undo history etc. However it is true that currently there is no proper user-facing error reporting in place. This should eventually be fixed by pre allocating everything that is needed to display a useful error message at program startup. This is vaguely related to #70 because (multiline) error messages should be displayed as regular files.

**Comment by Pyrohh** [comment]
> Large parts of the editor are written in a library like fashion which could be reused elsewhere, hence simply terminating upon failure is a unacceptable.

Good point.

> However it is true that currently there is no proper user-facing error reporting in place. This should eventually be fixed by pre allocating everything that is needed to display a useful error message at program startup

Yes, this was one reason for opening this issue; it's easier to do what I mentioned above then design a scheme that gracefully deals with error.
