### ISSUE TITLE
Cannot display current set values

### ISSUE THREAD

**Issue by rich-coe** [martanne/vis#156]
There doesn't appear a way to display the current value settings of the editor.
:set all  -- display all settings
:set     -- display all settings set by the user (from the default)

**Comment by martanne** [comment]
vis has deliberately only very few options, most of them give immediate visual feedback:
* `syntax ...`
* `show ...`
* `numbers`
* `relativenumbers`
* `cursorline`
* `cursorcolumn`
* `theme ...`

Others seem fairly obvious during normal usage:
* `autoindent`
* `tabwidth`

The only option not immediately clear if enabled is `expandtab`.

By far the most important "options" are the current key bindings (including the ones from `:langmap`) which are available from `<F1>` or `:help`.

Please argue why you need your proposed commands. The added complexity does not seem to be justified.

**Comment by mqudsi** [comment]
Would you consider `set xxx` without a value returning the current value of `xxx`?

**Comment by mqudsi** [comment]
Oh, I forgot the reason: my primary motivation is `set syntax`. While visual inspection tells you if syntax is enabled, it's not obvious if it _should_ be enabled but isn't (i.e. syntax is set but not supported, lpeg missing, etc) or if it's set to one filetype when it should be another.

**Comment by anddam** [comment]
I'd like a getter for the option as well. In my case I wanted to check what filetype was set and could not find a way to do.

If this adds too much complexity (I have yet to look at the `set` related code) maybe this belongs to a featured plugin?

**Comment by Yodzorah** [comment]
@martanne, another use case is custom options. For example, I have a boolean option `eofline` which indicates whether to add an empty line at EOF on file save. I often change this option, too, and when I forget what value it has, the only way for me to check it is to save unsaved changes, which is not cool at all. This issue may not seem necessary, because most of the existing options don't need it, but it really changes things when it comes to customizing vis and writing plugins. One of the good things about vim is that it has huge plugin base, almost anything anyone ever wanted they could install and enjoy. And that's because vim cared about what will happen is some day there will be an option whose value is _not_ obvious. You want huge plugin base for vis satisfying everyone's needs and making vis popular, right?
