### ISSUE TITLE
Vis can't open pseudo-devices, and issue a wrong error message

### ISSUE THREAD

**Issue by jvoisin** [martanne/vis#17]
```
$ vis /dev/null
Can not load `/dev/null': Is a directory
```

**Comment by martanne** [comment]
I agree that the error message is misleading. At the moment it is printed based on errno, I could change it to ENOTSUP resulting in "Operation not supported".

As for the editing of device files, what use case do you have in mind? Among other things it is currently not allowed due to the way saving is implemented which would likely screw up the system.

**Comment by jvoisin** [comment]
I just wanted to see how vis reacted to device files :)

**Comment by martanne** [comment]
The error message should be better now. I will reconsider the handling of device files when I'm reevaluating the approach to saving.
