### ISSUE TITLE
Structural regular expression support

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#219]
The sam command:

```
:2,3
```

should select lines 2 and 3.

Instead, only line 2 is selected.

**Comment by martanne** [comment]
Thanks for giving it a try! This particular bug should be fixed. I will leave the issue open for other structural regular expression related bugs (the `x` and `y` commands seem to not always work correctly).

More bug reports welcome ...

**Comment by martanne** [comment]
Ok some more comments / issues related to the sam integration:

* commands do generally not set the new dot, instead the editor returns to normal mode thus clearing any selections
* I/O related commands do not integrate properly with the undo/redo mechanism
* `s` (substitute) command should probably be implemented as an internal command instead of with `sed(1)`. It should support a count as in `s2/abc/def/` the following should also work: `s/(argA), (argB)/\2, \1/`
* multiple file support i.e. `X` and `Y` commands are currently broken?
* arbitrary text should be executable like in acme
* there should be a way to easily enter multi line commands (currently `<Ctrl-v><Enter>` in the command window followed by selecting the lines with `V` visual line mode must be used)
* there should be a way to keep the command window open

**Comment by martanne** [comment]
The last few commits should have improved structural regex support:
* sam's grouping semantic is now implemented, hence it is for example possible to swap words with:
```
,x/[a-zA-Z]+/{
      g/Emacs/ v/....../ c/vi/
      g/vi/ v/.../ c/Emacs/
}
```
* The `x` and `y` looping commands now set the registers `"&` and `"1-"9` with (sub-)expression matches which can be referred to in texts using `&` and `\1-\9` respectively. As a consequence the substitute command was dropped, it can almost completely be replaced by: `x/pattern/ c/replacement`. 
     
     The count specifier supported by sam was never implemented in vis. Eventually I would like to generalize the concept and apply it to all looping constructs either by modifying the syntax of `x`/`y` or `g`/`v` commands.
* If commands are issued from within visual mode new selections are created for every modification (akin to the dot setting in sam).
* It should be easier to enter multi line commands in the prompt. Suggestions to improve this further are welcome.

Multiple file support is still largely untested:

* The `X` and `Y` commands currently operate on windows, not files. Meaning that if a file is being displayed in multiple windows a given command will be executed once for every window. This is desired in certain cases (e.g. `:X q` to close all windows without unsaved changes) and unwanted in others (e.g. `:X 0i,/* ISC licensed */\n` to add a license template to the top of every file).
* The whole undo concept is file specific, the above insertion command can not easily be undone. Implementing an `u` command would at least give the possibility to `:X u` undo all changes.
* vis does currently not allow to switch windows while in visual mode. Should there be per-window modes?
* How should this all work with an eventual client/server architecture #130?

It would be nice to get some feedback about the current state of affairs from users familiar with sam/acme or more generally structural regexp.

I'm tagging a few people who reported issues in the past and/or engaged in related discussion on IRC @Screwtapello, @halfwit, @mbucc.

**Comment by martanne** [comment]
I'm closing this because the basic functionality (including the issue initially reported here) seems to work fine. The limitations regarding multiple file support mentioned in my last comment are still true. The wiki lists some [differences in syntax and behavior compared to sam](https://github.com/martanne/vis/wiki/Differences-from-Sam).

I'm still very much interested in feedback, ideas and individual bug reports regarding the structural regex support. A somewhat recent example of that was #774.
