### ISSUE TITLE
Odd multicursor encoding bug

### ISSUE THREAD

**Issue by DeltaHeavy** [martanne/vis#251]
Not sure if this is local to my implementation, so I'll add here that I'm running debian-8.

Sometimes, when multicursors move over whitespace (newline and space, that I've seen), an odd sequence appears in the place of the whitespace under the primary cursor.

The sequence is "M-b~V~H"

The following blocks are what shows up when the multicursor column is on the column of `e` in `include`, then when I move it right over the whitespace. It disappears again when I move the multicursor off the whitespace.

Let me know what other information I can give to help. Thanks!

```
#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <limits.h>
#include "sam.h"
#include "vis-core.h"
#include "buffer.h"
#include "text.h"
#include "text-motions.h"
#include "text-objects.h"
#include "text-regex.h"
#include "util.h"
```
```
#include <string.h>
#include <strings.h>
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <limits.h>
#include "sam.h"
#include "vis-core.h"
#include "buffer.h"
#include "text.h"
#include "text-motions.h"
#include "text-objects.h"
#includeM-b~V~H"text-regex.h"
```

**Comment by martanne** [comment]
Did you build it against a Unicode aware curses library (i.e. libncurses**w**)?

The problem is likely caused by e5ee84281b5dc984be1857e6bdb72b3895c6e3a4. Some terminals do not blink a cell if it contains a literal space. Therefore when the primary cursor is on a space we output an Unicode Full Block (U+2588) character instead. Your system does not seem able to display it though.

As mentioned elsewhere I'm not convinced this cursor blinking stuff is such a good idea ...

**Comment by erf** [comment]
@martanne - regarding blinking primary cursor, could it instead have a different color/style, perhaps equal to when the cursor is over an paranthesis or bracket.

**Comment by martanne** [comment]
@erf maybe, it is already [configurable via `lexers.STYLE_CURSOR_PRIMARY`](https://github.com/martanne/vis/blob/master/lexers/themes/dark-16.lua#L28). Using the same color as  for matching parenthesis is not a good idea because it will cause confusion when cursors are actually located on a parenthesis ...

**Comment by DeltaHeavy** [comment]
Linking libncursesw fixed the encoding issue, however now the whitespace is filled with a non-blinking block and the character to the right of it disappears until cursor'd-over.

In the same vein, the bottom selected line doesn't get a multicursor with `I`

**Comment by martanne** [comment]
Maybe it is a problem with your terminal emulator and/or font? vis generally assumes a working Unicode /UTF-8 environment.

What happens when you enter such a special character in vim (in insert mode type `<Ctrl-v>u2588`)? What happens if you do the same in vis?

I'm afraid I probably won't have time to further debug this. Maybe others can chime in and help?
