### ISSUE TITLE
Can't find default visrc.lua after changing PREFIX via `make PREFIX=$HOME/local install`

### ISSUE THREAD

**Issue by yggdr** [martanne/vis#269]
Hi,

after `./configure; make; make PREFIX=$HOME/local install` vis still looks in the default PREFIX (`/usr/local`) for its default configuration, instead of $HOME/local. So it can't find its default visrc.lua yielding a `module 'visrc' not found` error on startup.

**Comment by martanne** [comment]
Specifying a `PREFIX` at `make install` time can't (easily) influence the binary because it is already compiled. The correct thing to do would be to specify the desired path when running configure as in `./configure --prefix=...` or `./configure --sharedir=...`.

Unfortunately this currently also won't work. See #231 for details. A quick workaround would be to use:
```
export VIS_PATH=$HOME/local/share/vis
vis
```

**Comment by yggdr** [comment]
Thanks for the pointer, didn't find that issue while searching for "PREFIX".

That the binary can't (or rather shouldn't) be changed during `make install`: sure. But why isn't vis simply looking where its binary resides, then searches `../share/vis/` and the like, like many other programs do?

**Comment by martanne** [comment]
It does (see 9b3cd2462a48ca942309e24f511db2ea1fddc95b), but only on Linux or more appropriately on systems where `/proc/self/exe` points to the binary location.

If there are non-ugly solutions for other platforms, I'm willing to accept patches ...
