### ISSUE TITLE
Macro crash when recording @@ and playing it back

### ISSUE THREAD

**Issue by erf** [martanne/vis#285]
Ok, you should probably avoid doing such a silly thing, but i found a way to crash Vis by recording `@@`and playing it back with `@@`. 

As a side note, would be fun if you were able to repeat macros by prepending a number.

**Comment by martanne** [comment]
Not enough information! Please provide detailed steps to reproduce. And yes vis' macro support is currently rather rudimentary.

**Comment by erf** [comment]
ok.. just open vis and press `qq@@q@@`

**Comment by martanne** [comment]
Better, now I actually understand what you are doing (and what you meant with recording `@@` and playing it back). Always be explicit when reporting bugs! If in doubt provide more information than you think is necessary!

The problem here is infinite recursion, did I already mention that macro support is currently rather rudimentary ... ?

**Comment by erf** [comment]
Alright! Yes you did.. I would think recursion was the problem yes, just thought i mention it. Feel free to close it.
