### ISSUE TITLE
Entering command mode causes redraw/flicker of entire window

### ISSUE THREAD

**Issue by rwcarlsen** [martanne/vis#327]
Everytime I enter command mode (i.e. type ":" from normal mode), the entire window buffer is redrawn and flickers in a distracting way.

**Comment by martanne** [comment]
The problem seems to be related to window resizing, which happens as a result of the new command prompt window.

In general vis' display code assumes that redraws to its internal data structures are cheap and the latest drawn state can then efficiently be "blitted" onto the screen by only updating the damaged screen parts.

For the curses backend this translates into a series of `wnoutrefresh` calls followed by a `doupdate`. Due to the assumed double buffering performed by curses this should do what we want. However the window resizing seems to interfere with this. At first I suspected the [`erase`](https://github.com/martanne/vis/blob/39e089cc057f141ed440635493a041dc321eb2c3/ui-curses.c#L788) call causes the problem, but removing it does not seem to improve things.

I don't have time right now to further look into this, possibly I will have to check how the double buffering in libcurses is actually implemented.

@rgburke has contributed some display related patches, maybe he knows right away what the problem is.

**Comment by rgburke** [comment]
I'm not sure I can offer an explanation for the problem but I can offer an observation.

For the past few months I've played around with vis in Ubuntu using the GNOME Terminal and in FreeBSD using the xfce4-terminal, simply using the default settings in both cases. I've never noticed any flickering before when using vis and I couldn't reproduce it in these environments even when typing :<Enter> repeatedly in quick succession.
Out of interest I installed urxvt on both systems and began playing around with vis. It was at this point I noticed it would occasionally flicker when opening the command prompt.

I'm speculating at this point, but I suspect the issue may be related to the terminal emulator used. It would be interesting to know which terminal emaulators are used by those who have observed this issue.

**Comment by Screwtapello** [comment]
I don't have a lot of terminals handy, but:

- xterm 324 does not flicker when opening the command-line at 80x25, but it does when maximised, and it does flicker a bit when resizing the window
- gnome-terminal 3.20.2 never flickers when opening the command-line, but does when resizing the window
- tmux inside gnome-terminal seems to be much like native gnome-terminal
- pterm 0.67 never flickers when opening the command-line, but flickers heavily during resize
- terminology 0.7.0 never flickers when opening the command-line, but flickers heavily during resize

I can't find a way to make nano or vim readjust their contents like vis does, but in Vim I can open multiple panes and drag them with the mouse and it's all buttery-smooth, even in xterm. Vim and nano also both flicker slightly when resizing the terminal, for both xterm and gnome-terminal.

It's probably worth noting that gnome-terminal and xfce4-terminal both use libvte to provide the actual terminal rendering, so it's not surprising they'd have the same behaviour. Other terminals that might be worth testing are rxvt, st, and konsole.

**Comment by rwcarlsen** [comment]
I've been using vis with urxvt (where I noticed the flickering).
 xfce4-term is also smooth for me.

**Comment by martanne** [comment]
Things might have improved with the recent display code changes? It seems to work smoothly for all environments I care about. If it doesn't for you, then please report what kind of terminal emulator you use.
