### ISSUE TITLE
[discussion] More features from vim?

### ISSUE THREAD

**Issue by sshbio** [martanne/vis#332]
[TL;DR] Discussion on vim options that would be nice to have, some may be easy to implement.

There is no hurry, answer when you want/can/never... it is not an issue if it takes (a life) time!

I think I have seen on issues or the mailing list that you were busy right now, and this is really not urgent: just an open discussion to anyone interested, and not a wishlist (if I really want something I just have to fork, implement, pull!).  During these holidays, hopefully I will have time to contribute with code a few.

1: Here are some features that looks to be easy to add:

- [scrolloff](http://vimdoc.sourceforge.net/htmldoc/options.html#'scrolloff'): Addition the value of scrolloff (default 0) to the position of cursor while checking if it overflows?
- [wrap](http://vimdoc.sourceforge.net/htmldoc/options.html#'wrap'): Instead of inserting a newline onscreen, dropping the end of the line?
- ignorecase / [smartcase](http://vimdoc.sourceforge.net/htmldoc/options.html#'smartcase'): checking if the search string contains uppercase and set flags to sed and C libraries used?
- [listchars](http://vimdoc.sourceforge.net/htmldoc/options.html#'listchars'): calling configuration options rather than hardcoded ones?
- [insert mode] [C-x C-l](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-X_CTRL-L) Just like c-n, but with whole file piped to vis-menu, and in vertical layout (if any).
- ~~[insert mode] <C-x><C-f>: path relative to current file path?~~ [EDIT]: Already implemented, sorry.

2: There are features that may be more complex, but that I miss from `vim` while using `vis`:

- [insert mode] [C-e](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-E), [C-y](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-Y): I may be able to do this in lua, but I do not know vis source enough to do this.
- Command completion: I do not know if it would be hard to do: maybe while tab is pressed:
  - if it is `empty`: complete keyword;
  - if it is `set`: complete option;
  - if it is `e` or anything that take a file as argument: run vis-open;
  - if it is `set syntax`: complete syntax.
- [incsearch](http://vimdoc.sourceforge.net/htmldoc/options.html#'incsearch') and [hlsearch](http://vimdoc.sourceforge.net/htmldoc/options.html#'hlsearch'): Once incsearch is implemented, hlsearch may be more easy.
- Buffer management: [:ls](http://vimdoc.sourceforge.net/htmldoc/windows.html#:ls), [:bn/:bp](http://vimdoc.sourceforge.net/htmldoc/windows.html#:bn): It may be reorganizing the whole buffer management part, maybe this would fit while designing the client-server architecture?

3: This may not be possible to do in lua without modifying the C source:

- Customizable sidebar: adding more columns to sidebars or highlighting numbers would allow to add diffs, syntax checkers, display marks, ctags... marks in buffer.  These may be complex features to add, but the part to add to the vis source may be limited.  Moreover, it may share code with the already well designed number sidebar.
- [Undo tree](https://github.com/mbbill/undotree/blob/master/plugin/undotree.vim#L858-L1033): I do not know how complex this would be.  Maybe there can be some way to parse the history from lua, without extension, but I do not know how vis store these informations.  This is mainly because I get quickly get lost while trying to undo with g+/g-.

4: This may be much more complex to do by altering the C source, and may better be done with lua instead:

- Omnicompletion by using the lexers data.
- Snippets: It could be done through a lua function that set a binding in normal mode, but I am not sure about performance: Basically: while word entered, delete as many characters (<kbd><C-h></kbd>, insert the new string, with eventually a way to manage snippets with fields, but this can really be done in lua.

I really fear to bloat vis, and do not want to make it becoming vim.  So if there is anything that is out of scope, or feels too complex to you, I would clearly prefer that you refuse it.  Also, I prefer you to work on the features you want / already planned, rather on those I want.

**Comment by martanne** [comment]
Yes I'm busy and won't have much time for vis during the next 2-3 months.

In general we should be careful not to add unnecessary bloat. Most of the "plumbing" stuff should be done in Lua. Also personally I'm more interested in ways to integrate more sam/acme/Oberon inspired ideas, rather than copying vim features.

Having said that, each patch/pull request will be considered individually.

Things from your list which will be more difficult to implement properly than you might expect:

* line wrapping and horizontal scrolling are not likely to be supported because vis doesn't currently keep track of line boundaries, implementing this efficiently will be tricky.
* incsearch, this will require some form of concurrency. In the long term I would like to always keep the editor responsive irrespective of what it currently does. All tasks should be interruptible. This should extend to async plugins. This will require some architectural changes. The core data structure should be tuned to be more easily shareable, merging the possibly diverging text states won't be easy.
* buffer management is intentionally primitive as these things should be reconsidered when introducing a proper client/server architecture see #130.
* ignorecase / smartcase: although sometimes useful, one could argue that this falls under: explicit is better than implicit. Also there would have to be a nice integration into the structural regular expression syntax. The obvious syntax: `x/pattern/i` is already taken by the *i*nsert command. Vim uses an ugly and non standard `\c` escape sequence inside the pattern.

Features which should be done in Lua (if at all), they might require changes to the Lua API:
* Undo Tree visualization
* Snippets
* Quickfix functionality
* Anything using the LPeg lexer data (obviously since these are implemented in Lua)

As you noted for these the sidebar and more generally the display code should become more flexible.

Stuff from your list which upon first thought seems unnecessary to me:
* `scrolloff`
* C-x C-l as well as C-e and C-y in insert mode
* command completion, the vis way is to only have very few options in the first place. See also #25, #70 and #100

**Comment by sshbio** [comment]
Thank you for this very complete answer.  I will update the list accordingly tomorrow. I am glad and surprised how far you plan to bring vis.

I have a lot to learn by reading its source and the issues, which should keep me from opening useless issues.
