### ISSUE TITLE
difficulty mapping '

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#344]
these commands fail:

    vis:command('map! normal \' `')
    vis:command("map! normal ' `")

this command works:

    vis:command('map! normal "\'" `')

**Comment by sshbio** [comment]
Maybe this is due to vis having its own, simple parser for `:` commands: maybe the `'` character is interpreted as "begin quote": `map! normal '` looks for matching `'`, but find nothing, so abort the mapping.

Whereas ``map! normal "'" ` `` is a `'` character double quoted, and then a `` ` `` character, that requires neither quoting or escaping.

**Comment by sshbio** [comment]
It could then be convenient to have a way to map vis commands to keys in lua directly.  There is `map(mode, key, function)` in the [API](https://github.com/martanne/vis#lua-api-for-in-process-extension):

> map a Lua function to key in mode

Maybe it can be used in combination of `feedkeys(keys)`:

> Interpret keys as if they were read from the keyboard. If called from a key handling function, the keys will only be processed after the current key handling function has returned.

With something like ``map(MODE_NORMAL, "'", feedkeys('`'))`` (not tested yet...).

**Comment by aeosynth** [comment]
the failing commands still fail, although the first works interactively

**Comment by martanne** [comment]
Some of your commands do not make much sense.
```
map! normal \' `
```
Would be correct for interactive usage. The opening quote needs to be escaped. Then you have to consider the Lua escaping rules regarding `\`. The same commands in Lua looks like this:
```
vis:command("map! normal \\' `")
```
