### ISSUE TITLE
complete nested filenames

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#347]
request: filename completion working in nested directories, not just the current directory

**Comment by martanne** [comment]
Not sure whether this is what you wanted? But now it can at least be tweaked more easily.

The shell script could probably be improved, @Screwtapello, @TieDyedDevil, @rgburke any suggestions?

**Comment by rgburke** [comment]
`vis-complete` looks good. A couple of thoughts come to mind after playing around with it:

- At the moment it's only possible to complete paths below the current working directory. For example, typing `:e /home` and then entering `<C-x><C-f>` is not possible. It would be nice if any path could be completed.
- Performing a full recursive search is expensive when higher up in the directory hierarchy. Opening vis in my home directory I was able to trigger a find command which returned ~ 40,000 results and took several seconds to run. Perhaps one option could be to make `vis-complete` more like a navigtor so that the user can navigate through the filesystem to their file i.e. The user can select a file to use or a directory to traverse into.
