### ISSUE TITLE
request: abbreviations

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#348]
vim [abbreviations](http://vimdoc.sourceforge.net/htmldoc/map.html#Abbreviations) are simpler than snippets, and slightly different from mappings. the characters are inserted as typed, and expanded when a non-keyword character is typed. for example, in vim, `abbr co constructor` lets me expand `co<Space>` to `constructor`, while letting me type `const` normally.

**Comment by sshbio** [comment]
I was interested in snippets, and here is the answer I got: https://github.com/martanne/vis/issues/332#issuecomment-222535809

> Features which should be done in Lua (if at all), they might require changes to the Lua API:
> 
> - Snippets

A current workaround for now could be a function creating mappings ending with space, like `function abbrev("co", "constructor")` mapping `co<Space>` to `constructor<Space>` in insert mode.

**Comment by aeosynth** [comment]
yes you can emulate it with insert mode mappings, but the way keys are *not* printed is distracting

**Comment by aeosynth** [comment]
are there any lua plugins to look at as examples? `vis.lua` and the lexers/themes are the only places lua is actually used.

**Comment by sshbio** [comment]
> *not* printed

This is sure distracting.

I am not aware of any "plugin" yet for vis: the lua language provide [modules](http://www.lua.org/manual/5.1/manual.html#pdf-module) and vis could rely on this to make plugins (https://github.com/martanne/vis/issues/331#issuecomment-225852239).

@joshaw has some nice resources in [his dotfiles](https://github.com/joshaw/dotfiles2/tree/master/vis).

Otherwise, I looked for [vis.lua in github search](https://github.com/search?p=2&q=%22visrc.lua%22&ref=searchresults&type=Code&utf8=%E2%9C%93), but it seems that I am really spamming this search with my statically generated website hosted at github!

I do not have any advanced configuration for vis yet.

**Comment by aeosynth** [comment]
i implemented `abbr`:

https://github.com/aeosynth/dot/blob/master/vis/abbr.lua - implementation
https://github.com/aeosynth/dot/blob/master/vis/visrc.lua - usage

disclaimer: i do not know lua

i use `feedkeys('<Left><Right>')` to trigger a redraw

abbreviations are triggered with both space and open parens. i tried mapping newline, but that broke auto indent. there is no way to see which key triggered the mapping, so mappings are created for each key.

i'm not sure how to proceed with this - make a pr? a wiki page for plugins?

**Comment by sshbio** [comment]
Nice to see another visrc!   I would like to implement snippets, but I'm not sure I can.  This will be useful for this.

**Comment by aeosynth** [comment]
for the moment i disabled abbreviations, as there are too many caveats. i think we need a better api first.

**Comment by martanne** [comment]
I think this should be possible to implement with the [current Lua API](http://martanne.github.io/vis/doc/).
