### ISSUE TITLE
Window local mapping from lua in command prompt

### ISSUE THREAD

**Issue by joshaw** [martanne/vis#355]
This isn't really an issue at the moment, more a conceptual question.

I'm looking to remap `<Tab>` in the `:`-prompt. Since this is implemented as a single line window, I assumed I could open the prompt and then `win:map()` but that is not working. I have the following
```
function showprompt()
    vis:feedkeys('<prompt-show>')
    vis.win:map(vis.MODE_INSERT, '<Tab>', tabfunc)
    vis:info(vis.win.file.name or 'nil')
end
vis:map(vis.MODE_NORMAL, ':', showprompt)
```

This always shows the file name of the window which is active (not the prompt window) even though the prompt is displayed, and so the window local mapping is unavailable. Is this expected behaviour? Is there a better way you can think of?

Thanks.

**Comment by martanne** [comment]
I haven't actually tested it, but the problem is that `feedkeys` will only take effect after the current key handler `showprompt` has returned. This is documented as such in the README. However I agree this behavior is non-intuitive and confusing, it should be changed.

Your file name printing reveals that `<prompt-show>` wasn't yet interpreted. `vis.win` still points to the regular non-prompt window. Hence the `<Tab>` mapping was set up there.

**Comment by joshaw** [comment]
Ah, I see. I hadn't quite understood that part of the README. I now understand, thank you, though I agree, it's not exactly intuitive.

**Comment by martanne** [comment]
As of c0e86f811b3a8e4f45768db86e97d1b0fda5616f this should now work as expected? The changes affected the core input handling code and were only minimally tested i.e. some bugs might have crept in.
