### ISSUE TITLE
ci" unexpected behavior?

### ISSUE THREAD

**Issue by sicher** [martanne/vis#358]
Buffer content:

```
This is a "line"
Another "line"
        ^
```
Cursor at ^. In this case ci" results in:

```
This is a "line"
Another "      ^
```

This seems like a bug. Also, with the cursor further to the left on the line and ci" interprets the "" pair to be used as the last " on line 1 and the first " on line 2. This goes for all locations on line 2 up to the first ", resulting in:

```
This is a "line""line"
                ^
```
I think vim does not allow strings to span multiple lines. Also, it automatically searches forward to the next quote-pair on the current line, which is handy. In vim, the result would be:

```
This is a "line"
Another ""
         ^
```

For all cursor positions on line 2 up to, and including, the last "
Any design thoughts on how vis should behave here?

**Comment by martanne** [comment]
Thanks for the detailed report, the first case you mention is clearly a bug. It affected all inner text object variants when the cursor was on the opening delimiter and should be fixed by 819ef09d1cd9e77a3ffb681fb2e8508e62ffef1c.

I did not realize that vim does not allow strings to span multiple lines. I'm not yet sure whether I like that, in general vis operates on ranges and tries to avoid "line-based" behavior. Having said that, I have to admit that the search forward to next quote-pair is useful in some cases.

This should be revised in the future, right now I don't have the time anyway.

**Comment by sicher** [comment]
Ok, thanks. If I get the time to have a look I'll let you know.

**Comment by erf** [comment]
I think there is a bug since 819ef09, if you have the following ( notice the dot ).
```
'test'
'.test'
```
Placing the cursor on the first `'`on the second line, it matches with the last `'`on the first line.
