### ISSUE TITLE
search broken in binary file

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#359]
i opened a `.png` and `.jpg` file in vis, search behaved strangely / failed. opened same files in nvim, search worked fine.

i can look for a simple test case, but i assume this will behave similarly in any binary file.

**Comment by martanne** [comment]
This is currently a known limitation due to the fact that we use the `regex(3)` interface of libc which can't deal with NUL bytes. To properly fix that we need an internal regex engine based on some kind of iterator API. The [sregex](https://github.com/martanne/vis/tree/sregex) branch might work (I haven't actually tested it in a while).

In general the basic functionality for binary file editing is there, but it will require some polish to make it really usable in practice. In particular most basic cursor motions expect that they are dealing with UTF-8, there should be some kind of binary mode which switches to byte based access.

Once I have more time, I will come back to these issues.
