### ISSUE TITLE
C-c for exiting command line prompt

### ISSUE THREAD

**Issue by vwyu** [martanne/vis#361]
Would it be possible to add &lt;C-c&gt; as another way of exiting the command line prompt? 

(Note that after 680a170, &lt;C-c&gt; can be used for returning to normal mode from insert mode or visual mode.)

**Comment by martanne** [comment]
Something like `:map! insert <C-c> <Escape><Escape>`  should work, I think. However it will also affect "regular" i.e. non-prompt insert mode. In particular it will always dispose all but the primary cursor. Generally not a problem for the command prompt, but probably not the desired behavior in general. Due to #355 it is currently not (easily) possible to change only command prompt mappings from Lua. You will have to change the [relevant C code](https://github.com/martanne/vis/blob/c61e4091d0d1bc9a3af2f11034f2c0716d302d99/vis-prompt.c#L170) directly for now.

**Comment by vwyu** [comment]
Thank you for the information.
