### ISSUE TITLE
`./configure --static` produces a dynamically linked file

### ISSUE THREAD

**Issue by xihh87** [martanne/vis#373]
Tried to build a static binary for vis on branch master for latest commit:

./configure --static
make

Got a dynamically linked file instead of a statically linked file.

[vis-bug.txt](https://github.com/martanne/vis/files/425654/vis-bug.txt)

**Comment by Paspartout** [comment]
That's probably because it only prepares make for static linking, by checking if the compiler flags work.

For compiling a static binary I suggest trying `make standalone`. This downloads every needed dependency for vis(including musl libc) and compiles everything needed from scratch. The main problem is that some distributions only ship dynamic libraries without their 'static .a' counterparts which makes static linking impossible.

**Comment by martanne** [comment]
Yes the `--static` option of configure is just there to disable the PIE option because GCC for some reason doesn't want to generate statically built position independent executables. (There are various patches floating around to enable it, but I'm not sure whether they have finally been merged into upstream GCC).

To actually perform static linking you should set your `CFLAGS`/`LDFLAGS` appropriately. The [`make standalone` implementation](https://github.com/martanne/vis/blob/d41e8af294d0e23820576a8612a7ec1b37482dee/GNUmakefile#L187) also does it that way.
