### ISSUE TITLE
Join behaviour

### ISSUE THREAD

**Issue by erf** [martanne/vis#374]
I'm a bit curious about the `join` behavour - which now adds an extra space when joining lines, i would prefer it didn't ( although this is also the behaviour in `vim` ) .

For example if i have the following ( no space at line end ):
```
.do
.something
.funny
```
Selecting these three lines and pressing `J` results in:
```
.do .something .funny
```
I would prefer:
```
.do.something.funny
```

**Comment by Shugyousha** [comment]
On Tue, Aug 23, 2016 at 01:03:19PM -0700, erf wrote:
> I'm a bit curious about the `join` behavour - which now adds an extra
> space when joining lines, i would prefer it didn't ( although this is
> also the behaviour in `vim` ) .

vim does the same but vim also allows you to join lines without inserting
a space by using the gJ command. I think implementing the gJ command in
vis would be handy and shouldn't be too hard. At the moment I don't have
time to do it myself though...


Cheers,

Silvan

**Comment by sshbio** [comment]
Maybe I'm wrong, but `gJ` is just like `Jx`?

Then `gJ` can be bound to `Jx` in the `.visrc`.

Otherwise it may be done in the C source as you said.

**Comment by Shugyousha** [comment]
On Tue, Aug 23, 2016 at 01:27:18PM -0700, Josuah Demangeon⠠⠵ wrote:
> Maybe I'm wrong, but `gJ` is just like `Jx`?
> 
> Then `gJ` can be bound to `Jx` in the `.visrc`.

I like the idea!

It only works if you do it line by line though (and then undoing it
splits up the actions again, i. e. you have to undo twice to first undo
x and then J). If you use visual mode the mapping will only remove the
last joined space. That means in case of

1
2
3

when doing gJ in visual mode (when having the mapping) it will result in

1 23

Maybe there is a a way to enforce a line-wise application of the whole
alias in visual mode. Not sure. A C implementation may still be easier
and faster to do.

**Comment by sshbio** [comment]
Oh, yes: more than two lines to join and cleaner undo history, I get it :)

**Comment by erf** [comment]
Line 203 in `vis-operators.c` inserts the extra space it seems .. If i could pass an argument there with an optional `avoid-insert-space-bool` it would be an easy fix, but the `args` in the OperatorContext is an union with the value `i` already set .. Maybe the `args` should be a struct ? But I am not very familiar with c and the vis internals so maybe somebody else have a suggestion .. It doesn't seem like a good idea to rewrite the `op_join` method for just a small fix.

**Comment by Shugyousha** [comment]
On Wed, Aug 24, 2016 at 12:50 AM, erf <notifications@github.com> wrote:
> Line 203 in vis-operators.c inserts the extra space it seems .. If i could
> pass an argument there with an optional avoid-insert-space-bool it would be
> an easy fix, but the args in the OperatorContext is an union with the value
> i already set .. Maybe the args should be a struct ? But I am not very
> familiar with c and the vis internals so maybe somebody else have a
> suggestion .. It doesn't seem like a good idea to rewrite the op_join method
> for just a small fix.

vis is using two different key bindings and associated methods to
perform the action depending on whether in visual mode or not.

1. Normal mode: it uses the "join" (main.c) function which calls
vis_operator (vis-operators.c) with VIS_OP_JOIN.

2. Visual mode: It uses the "operator" (main.c) function which calls
vis_operator with the second argument  set to arg->i (which is
VIS_OP_JOIN in our case).

Both are very similar. The only difference is that join get's a count
before calling vis_operator and then moves the cursor (one line down).

The easiest way to implement it would be to copy op_join, modify it to
not add a space and add a key binding. This is rather hacky and
unclean.

To fix it properly we would have to think about a way to get more than
one argument (== extra arguments like a boolean in our case for
example) to vis_operator. This change is rather large and would mean
that potentially a lot of code regarding the operators would have to
change.

Thinking about a clean solution to this problem is worth it for sure.

**Comment by erf** [comment]
I wonder if `func` on line 59 of `vis.h` would benefit being a `variadic function` ?

**Comment by Shugyousha** [comment]
Ah, turns out vis_operator was a variadic function already. I missed that :) Looks like a good solution to me
