### ISSUE TITLE
Huge delay after pressing Esc-key when exiting INSERT mode

### ISSUE THREAD

**Issue by maribu** [martanne/vis#376]
Hi,

if I just quickly want to save changes and I type in the sequence "Esc", ":", "w", "Enter" without waiting at least 2 seconds after pressing "Esc", vis does not exit INSERT mode but instead inserts the text "<M-:>w\n" (where "\n" stands for end of line). Is there any way to configure vis to instantly exit INSERT mode when "Esc" is pressed?

Thanks,
Marian

**Comment by Shugyousha** [comment]
On Thu, Aug 25, 2016 at 06:20:20AM -0700, maribu wrote:
> if I just quickly want to save changes and I type in the sequence
> "Esc", ":", "w", "Enter" without waiting at least 2 seconds after
> pressing "Esc", vis does not exit INSERT mode but instead inserts the
> text "<M-:>w\n" (where "\n" stands for end of line). Is there any way
> to configure vis to instantly exit INSERT mode when "Esc" is pressed?

I have a similar (maybe the same) issue though it happens mostly when
I'm using vis in a VM, making me think it's a timing issue.

Are you exaggerating or do you really have to wait for 2 seconds? For
me it happens when I press ESC and then another command (like 'k')
in very fast succession. IIRC I only have it happen when I use vis in
a VirtualBox VM though.

**Comment by maribu** [comment]
I just tested if this is also happening in a real tty, not in a x.org terminal emulated. At first I thought it was xfce4-terminal's fault, but I noticed it is only happening when using tmux.

I think I also found a solution here: http://superuser.com/questions/942677/consequences-of-escape-time-0-tmux-setting

Sorry for not checking this out before asking here!
