### ISSUE TITLE
map non-printable sequences

### ISSUE THREAD

**Issue by morphles** [martanne/vis#386]
Not sure if possible already (if so then help should be updated). On vim I have
    `:imap jj <esc>`
that is quite comfortable way to leave insert mode for me, similarly I have
    `:nmap ss :w<cr>`
for saving. Seems it is not possible in vis currently, and that has quite some limitations. I also tried using litteral characters by prefixing them with ctrl+v, but that also does not work.

**Comment by martanne** [comment]
The `:help` or `<F1>` output also lists all available symbolic keys. For example you will want to use `<Escape>` instead of `<esc>`. However, your first example likely won't work. In vim it would only trigger when `jj` is entered in short succession, right? Vis doesn't consider the typing speed when evaluating key mappings. Hence, with the following setting
```
:map insert jj <Escape>
```
you have essentially disabled the `j` key for regular input. Because it is a prefix, vis will wait until another character is entered.

Your second example would look like this:
```
:map normal ss :w<Enter>
```
But again because there already exists a mapping for `s` this won't work. You would have to either manually  unmap the existing default mapping (using `:unmap normal s`) or force the new mapping with `!` (which implicitly unmaps all existing prefixes).

**Comment by morphles** [comment]
Thanks, those do indeed work. This timing thing is very nice actually, but can be done without at least somewhat. But not with current situation. Not the first application I encounter which blocks sequential binds by executing first that matches. Like for s. I understand this gives some simplicity, but it is incredibly limiting, it should not execute binds until it is sure that current sequence is not a longer bind. Thought insert mode even works correctly, like in vim. As with my bind you can type something like `jhon` in insert mode without problems, but that is because just `j` is not bound to anything in insert mode. As I understand if I had it bound, I would be unable to use `jj` with current implementation (though such discussion for insert mode is a bit moot). In any case mappings should try to match longest sequence and taking second example, `s` is bound and `ss` is bound, typing `ss` should trigger second bind, while typing just `s` should not do anything, but typing `s<Anything else>` should trigger `s` and do whatever appropriate with `<Anything else>` that way behavior with default binds does not change, and gives way more flexibility and extensiblity with bind usage. Timeout as in vim is not terribly needed, and in any case I believe it is used to forget sequence as part of bind (that is if you type part of long bind, pause and continue bind will not trigger). But I do not even use timeout (well it is set but to something like 1000s, effectively disabled), it not that big of a problem with sensible sequences and described handling.

**Comment by martanne** [comment]
[This patch](http://sprunge.us/RKhX) should implement the behavior you prefer.

I still don't particularly like the fact that the editor shows no indication that it is waiting for further input. For example with your first example:
```
:map insert jj <Escape>
```
entering a `j` in insert mode will do nothing, then if you press an additional key it will insert both at the same time. For comparison vim seems to immediately display the `j` and then after a timeout either insert it and advance the cursor or in case `<Escape>` was pressed hide/remove `j` again and switch mode. This kind of visual feedback is way too complicated and will not be implemented!

I suppose it would be possible to display something in the status bar (similar to vim's `:set showcmd`). Although showing the input queue content might be problematic because it could contain "editor action keys" (e.g. `<till-left>`) which would probably confuse users.

I don't really use mappings and the default configuration should be non-ambigious anyway. Hence, I have not that strong opinion about it.

@aeosynth you seem to use mappings extensively, maybe you could give the patch a try? Also it should fix your issue as reported in #271.

**Comment by aeosynth** [comment]
what is the command to apply the patch?

**Comment by erf** [comment]
@aeosynth https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

**Comment by aeosynth** [comment]
patch solves my issue :+1:

**Comment by martanne** [comment]
The question was more whether it would cause other issues. We will find out, I guess ...
