### ISSUE TITLE
[Request] Add file:fullpath to the Lua API

### ISSUE THREAD

**Issue by lxyd** [martanne/vis#407]
There is a `name` field in the `file` object, but sometimes it is usefull to also see the full absolute path to the file from the root directory.
Propbably there would be also usefull to export `to_absolute_path(…)` function somehow.

**Comment by martanne** [comment]
Currently the returned name is always relative to the process working directory. I agree that this is probably not optimal from an API design perspective:
```lua
print(win.file.name) -- relative
vis:command('cd /')
print(win.file.name) -- absolute
```
It was done that way to save display space in the window status bar. We should probably always return the absolute path as used by vis internally and let the Lua code decide how to display it. The problem here is that by default Lua as no concept of a working directory. Hence, we could either depend on a POSIX wrapper like [luaposix](https://github.com/luaposix/luaposix) or implement something like `vis:getcwd()` to avoid the additional dependency for this single function.
