### ISSUE TITLE
Weird behaviour with structural regexes

### ISSUE THREAD

**Issue by Screwtapello** [martanne/vis#408]
# Steps to reproduce
1. Start vis, enter the following content:

        a\sb
        aa\sbb
        aaa\sbbb

1. Run the following commands:

        :,x/\\s/
        :,x/\\\\s/
        :x/s/ c/n/

1. The document vanishes, which (I think) is a different bug. Type 'gg' to get it back.
1. The document should now be as it was initially, except with all the `\s` replaced with `\n`.
1. Hit 'u' to undo.

# Expected results

The last search and replace is undone, reverting all the `\n` back to `\s`

# Actual results

Nothing happens. Repeated bouncing on 'u' does nothing.

**Comment by martanne** [comment]
Thanks for the report, as discussed on IRC this was mostly a display issue. The problem was that the cursor location was deleted by the change command. The now invalid cursor position was then "displayed", effectively scrolling beyond the end of the file. As far as I can tell undo is unaffected.

With the latest commits what you want can be done in a single command `:x/\\s/c/\\n`. Splitting that into multiple commands as in your example:
```
:x/\\s
:x/s/c/n
```
also works.

However your example illustrates a more general problem. The first command creates a couple of selections. Then your second command once again applies to the whole file (because it is prefixed with `,` which is equivalent to `0,$`). This causes confusion because lots of overlapping selections are created. For now I consider this a "user error" i.e. if you instruct vis to create overlapping selections you get to interpret the result.

**Comment by Screwtapello** [comment]
Thanks for looking into it. I can confirm the latest version of vis behaves much more sensibly.
