### ISSUE TITLE
crontab -e fails to save changes

### ISSUE THREAD

**Issue by xcko** [martanne/vis#431]
EDITOR=/usr/bin/vis crontab -e opens the crontab for the user as expected, but all changes are discarded after :wq. Vim and vi work fine.

This is on linux crux 3.2
sudoedit works fine though.
vis v0.2-544-g5b689ba

**Comment by eworm-de** [comment]
Works for me...
```
% EDITOR=/usr/bin/vis crontab -e
no crontab for eworm - using an empty one
crontab: installing new crontab
```

**Comment by xcko** [comment]
Upon saving and quitting the changes are still there?

**Comment by eworm-de** [comment]
Yes. I updated my comment, see above.

**Comment by martanne** [comment]
Crux uses [dcron](http://www.jimpryor.net/linux/dcron.html) which [assumes that the file descriptor/inode remains valid when saving](https://github.com/dubiousjim/dcron/blob/master/crontab.c#L159) this is not the case for vis because we use `rename(2)` with appropriate fallbacks (that don't apply here, hence the problem). The vis behavior is similar to [`backupcopy=auto`](http://vimdoc.sourceforge.net/htmldoc/options.html#'backupcopy') in vim.

**Comment by martanne** [comment]
Can you confirm that as of 8ec5991a8fd4f053afa12d93f63b5a17f2ef3669 it works as expected? Make sure to install the most recent Lua files.

**Comment by xcko** [comment]
It works! Thanks martanne.
