### ISSUE TITLE
Change word and repeat with period

### ISSUE THREAD

**Issue by erf** [martanne/vis#44]
If you press c-w and enter some text, than press escape, and try to repeat this action with period, it only adds the last word, and does not change the current.

**Comment by martanne** [comment]
Thanks for the report! This is an interesting issue. 

It seems like all changes following a command which switches to insert mode should be repeated. In vis the affected commands are change (`c`, `C`, `Y`), append (`a`, `A`, `I`) and open (`o`, `O`). To fix this the changes in insert/replace mode should probably be recorded in an implicit macro which can then be replayed.

For example in vis, in insert mode typing `^wFOO` and then repeating it with a `.` will only insert `FOO` but not delete a word whereas in vim it will do both (delete followed by insert).

However certain movements should reset this "repetition buffer". As an example if in insert mode `foo<RIGHT-ARROW>bar` is typed and this is then repeated only `bar` should be inserted.

**Comment by erf** [comment]
I'm reading 'Practical Vim' now, and he mentions that his favorite action in vim is to use the dot operator to repeat an action, and mentions that Vim records what you do in insert mode, and i also find that a really good feature. You should also include (s, S) and (r, R) and any other insert action. You would probably just need to fill a register for that specific insert, i checked that Vim does not record arrow movements, but a implicit macro for even more recordings would be pretty cool.

**Comment by martanne** [comment]
With the latest commits, `c`, `C`, `a`, `A`, `i`, `I` should now more or less work as expected. Only *very* briefly tested though, further feedback would be appreciated ...

`o`, `O` and `r` aren't yet repeatable (due to the way input handling works, key handlers currently can't push new keys into the input queue which makes implementing them somewhat tricky).

The arrow keys are deliberately not treated specially i.e. they do not reset the repetition macro. 

Interaction with the undo/redo functionality could be improved (if a count is provided, the implementation switches repeatedly  in and out of insert mode which creates a document snapshot).

**Comment by erf** [comment]
Great work! Seems to work as expected. Are you adding <pre>s</pre>, <pre>S</pre> as well?

**Comment by martanne** [comment]
[`s` and `S` should already be recognized?](https://github.com/martanne/vis/blob/master/config.def.h#L210)

**Comment by erf** [comment]
you are correct. but there is a missing functionality, that is, if you visually select some words and then press c or s then you can't repeat that operation. that is if you go to the next line and press dot, you should be able to repeat the operation, from the current position, in the same range as the previous visual selection

**Comment by martanne** [comment]
I consider visual repeat a broken concept not worth supporting.

**Comment by erf** [comment]
Ok. No problem. Feel free to elaborate - or don't =)

**Comment by martanne** [comment]
`o`, `O` and `r` should now also be repeatable. `O` still has some problems, but I think it is good enough. I'm thus closing this issue.

I feel there is too much guesswork involved in visual repeat. The effort needed to get a correct (with regard to Unicode handling etc.) implementation is not worth it. Even more because I personally don't use it. Maybe your use case is covered by multiple cursors / selections?

**Comment by erf** [comment]
Great work. I agree and multiple cursors are much better !

**Comment by erf** [comment]
I have a question. It seems you try to avoid visual mode, and use multiple cursors instead, then why do you go into visual mode when you press Ctrl-N ? Could you just create new cursors and stay in normal mode ?
