### ISSUE TITLE
n count for macro

### ISSUE THREAD

**Issue by xcko** [martanne/vis#448]
In vis it appears that after recording a macro, using some n with @@ or @q,  it only runs the macro once.

Is this intentional? Is there a parallel feature that I can use instead?

**Comment by martanne** [comment]
While this should now work for simple cases, vis' macro support is in general rather poor (mostly because I hardly ever use them). For example macro execution will not stop when a motion isn't successful. Hence when you do something like `1000@@` for a macro which moves to the next line, it won't stop at the last line.
