### ISSUE TITLE
Colors weird after dc29c30

### ISSUE THREAD

**Issue by erf** [martanne/vis#456]
Colors are weird, mostly dark blue, after dc29c30 on macOS.

**Comment by martanne** [comment]
This is most likely because your terminal reports that it can change colors, when in fact it can not. What is your `$TERM`? What does `infocmp | grep ccc` yield?

The correct fix is to copy your current terminal description (as printed by `infocmp(1)`), remove the `ccc` capability, compile it to a new name, install it and then set `$TERM` accordingly.

Also complain to Apple.

**Comment by martanne** [comment]
This seems to be a [workaround](http://sprunge.us/KKVN), but in principle it is a terminal issue ...

**Comment by erf** [comment]
I'll leave a link here on [How to modify an existing terminfo](http://www.jbase.com/r5/knowledgebase/howto/general/common/CreateTerminfo/modify.htm) for reference.
