### ISSUE TITLE
overwriting symlinks issue

### ISSUE THREAD

**Issue by tonkazoid** [martanne/vis#47]
It seems like vis does not follow soft links? If you open a link with vis and save it, it'll overwrite the link.
```
touch file
ln -s file link
vis link
:wq
```

**Comment by martanne** [comment]
Hi, thanks for the report, you are not ignored. It is a known issue. Other (related) problems of the file save code include:

* hard links
* loss of original ownership
* failure if we have no write permission in the containing directory, but only to the opened file
* loss of extended attributes / SELinux labels etc
* `ENOSPC` behaviour
* making sure that the data is actually flushed to disk (e.g. `fsync`)
* ...

I need to figure out the "best practice" approach to writing a file such that it is both secure and robust. An idea is to prepend the new file content in front of the old one and then `ftruncate(2)` to the new size thus discarding the old content. However upon failure the new content has to be removed again from the front. This approach has the problem that other processes might see an inconsistent intermediate state which is why currently an atomic `rename(2)` is used. Mandatory file locks are cumbersome and not really working reliable in practice. So yes, it is a mess.

Unfortunately I'm currently really busy with other stuff and will most likely not have time to address this issue during the next couple of weeks.

**Comment by martanne** [comment]
Still not quite sure what the optimal approach is, but at least basic cases should now work as expected. Real world testing welcome ...

**Comment by z3bratabs** [comment]
When editing a symlink, you can only write to the file once. The first time, st_mtime gets updated correctly, but upon writing again to it, the following warning appears:

> WARNING: file has been changed since reading it

The problem seems to comes from this line: `vis-cmds.c`, line [580](https://github.com/martanne/vis/blob/master/vis-cmds.c#L580), `file->stat.st_mtime` doesn't match the actual modification time.

**Comment by martanne** [comment]
Does 697bc0ebc8178488cdb837b584b47d965b421b48 fix the issue?

**Comment by z3bratabs** [comment]
Seems to work perfectly, thanks for the quick update.
