### ISSUE TITLE
vis symlink breaks config

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#471]
i want a vis symlink in my `$PATH`, so i can rebuild without needing to `make install`, but when using the symlink, my config in `$HOME/.config/vis` is not used; instead, `/usr/local/share/vis` is used. i'm on arch linux, and `/proc/self/exe` is available.

**Comment by martanne** [comment]
I think the behavior you see is due to the fact that vis tries to read its files relative to the binary. That is the files from the `lua` sub folder of your build directory (not the ones from `/usr/local/share/vis`) are used. Adding a symlink won't change that, because the target (not the source) of the symlink is relevant. In any case the end of the `:help` output will list all directories which are being used.

Setting (and exporting) the `$VIS_PATH` environment variable should fix your problem.
