### ISSUE TITLE
Cannot combine vertical and horizontal splits

### ISSUE THREAD

**Issue by KolesnichenkoDS** [martanne/vis#473]
If I already have two vertical panes and I try to split one of them horizontally, vis makes all splits horizontal.

```viml
:vsplit
:split
```

Also, I didn't find vim's `splitright`/`splitbelow` analogues.

**Comment by josuah** [comment]
Yes, it is hrue, but I think it is [by design](https://github.com/martanne/vis/blob/master/README.md#user-content-non-goals).

The user is expected to do window splitting with multiple terminal in a window manager or with a terminal multiplexer.

@martanne also wrote a multiplexer that I use every day: [dvtm](http://github.com/martanne/dvtm).

**Comment by martanne** [comment]
Yes this is by design and won't change anytime soon. In the (distant) future your (terminal) window manager should take care of your editor windows (see also #130).
