### ISSUE TITLE
vis available under openSUSE

### ISSUE THREAD

**Issue by abaez** [martanne/vis#490]
I've made this a while back, but thought I should link here to help with the packaging release cycle of issue #484. The packaging uses the [openSUSE Build Service][obs], which can be used to make packages of multiple distributions, not exclusively to openSUSE or even rpm based. 

The build is currently using the git repository directly for the version release. You can find it [here][pkg] in the [home:a_z][a_z] repository.

[pkg]: https://build.opensuse.org/package/show/home:a_z/vis
[obs]: http://openbuildservice.org/
[a_z]: https://build.opensuse.org/package/show/home:a_z/

**Comment by martanne** [comment]
Thanks, are you familiar with the build service?

If I'm not mistaken it should be possible to build packages for openSUSE, RHEL, Fedora, Debian, Ubuntu, Arch and trigger them from github commit hooks. However, I quickly skimmed the documentation but couldn't find an example to do so.

We already a have [Debian](https://github.com/paride/vis/tree/debian/sid/debian) and [Arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vis-git) package recipes which could be imported. But I'm not sure how to configure the build service, do we need a different package for each distro (I hope not)?

**Comment by abaez** [comment]
I've recently been fooling around with the process in getting multiple distributions from the build. It's actually from the PKGBUILD framework of Arch that got me to the OBS setup. 

As far as I understand it, you can use the RPM spec and expand to incorporate other distros. I'll see if I can take a whack at this and report back at what comes out of it. 

At the same time (and hoping not to diverge too far from subject), I have been looking at doing an [AppImage] for vis. Sometimes, having the option for a quick local setup can help (eg: doing some unprivileged user coding).  

[AppImage]: http://appimage.org/

**Comment by martanne** [comment]
Please report back on your findings about OBS. It is not clear to me what happens if there are multiple build recipes (e.g. rpm spec files, maybe even for different rpm based distros? PKGBUILDs, Debian's rules/control files etc.) uploaded into the same package. 

The use case targeted by AppImage should already be (better?) supported by the results of `make standalone` and `make single` which build a self-contained statically linked binary.

**Comment by abaez** [comment]
On Fri, Feb 10, 2017, at 03:57 PM, Marc André Tanner wrote:








> Please report back on your findings about OBS. It is not clear to me
> what happens if there are multiple build recipes (e.g. rpm spec files,
> maybe even for different rpm based distros? PKGBUILDs, Debian's
> rules/control files etc.) uploaded into the same package.






I can completely understand the confusion over the OBS formatting. The
docs aren’t exactly great helping figuring out how to even use it.
However scavenging for some documentation a while back, I did find the
package formatting[1] reference. It states that you can have one RPM
spec for all rpm distros, the deb input files for debian based, and a
simple PKGBUILD for arch derivatives. What I have been curious of is
trying to put them all in one package. This is the part I’m unsure of.
I’ll try it this weekend and see what alchemy I get out of the one
package for all.






> The use case targeted by AppImage should already be (better?)
> supported by the results of make standalone and make single which
> build a self-contained statically linked binary.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].
> 







Ok. I should’ve definitely looked at the GNUmakefile. That’s quite a
cool option I didn’t know existed. I was thinking of AppImage case
solely with the notion of being able to distribute without compiling.
Though I don’t  think it’s even desired with the standalone|single
options here.



Links:

  1. http://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.package_formats.html
  2. https://github.com/martanne/vis/issues/490#issuecomment-279063851

**Comment by abaez** [comment]
Alright, so after experimenting a little, I found out a couple of answers to how to get the packaging working through OBS.

I've added the debian requirements to the package, which I've been experimenting with to getting the deb version integrated. However considering my lack in knowledge on the field, I don't really know more than documentation given on the [openSUSE wiki][1]. So I'll continue to strive to get the package built, on my spare time using OBS. As for the PKGBUILD for Arch, I have already added it to the main package as well on [home:a_z/vis][2]. The PKGBUILD only needs the repository enabled to function I believe. 

[1]: https://en.opensuse.org/openSUSE:Build_Service_Debian_builds  
[2]: https://build.opensuse.org/package/show/home:a_z/vis

**Comment by martanne** [comment]
I played around with it a bit. In my opinion the OBS documentation is quite poor. It would be nice to use their infrastructure (especially because they support non-x86 architectures) to provide nightly builds and run  the test suite. However, it is quite clear that the primary focus is to build openSUSE packages rather than providing cross distribution packaging infrastructure/services for upstream projects. Otherwise they would probably at least have a hello world example which builds packages for all supported distributions.

For test purposes I tried to build the Arch Linux package, but one of the dependencies (libtermkey) is only in the Arch community (rather than core or extra) repositories so that wouldn't work anyway. Furthermore, it complained about missing packages `obs-service-{tar,recompress,set_version}` this could probably be fixed by tweaking the `_service` file? Or by adding a `_service:set_version:PKGBUILD` which some other packages seem to use. But again the documentation seems to be lacking (or I was looking at the wrong places).

For now I personally don't want to spend more time on these package related issue. I hope distribution maintainers will eventually take care of it.

Thanks again for the openSUSE package, I added it to a new wiki page listing [distribution packages](https://github.com/martanne/vis/wiki/Distribution-Packages). Do you plan to submit it to the official openSUSE repository after release?

**Comment by abaez** [comment]
@martanne you have no idea how much I agree with the OBS documentation issue. I once tried to figure how to help them in the docs... I couldn't find the docs to learn the procedure how... 

Speaking of OBS doc woes, I was recently introduced to [bintray][1], which may be an option worth considering. 

As for the Arch issue, I think it has to do with how the local builds are run than how it works on the deployment server (which again, no docs to figure how to even get there). 

Finally, on the submitting to  the official repository, I probably will. Originally the package was for myself in learning how to use the OBS system, but there shouldn't be any harm in trying to get it officially integrated to make things easier for the **vis** community.



[1]: https://bintray.com/

**Comment by martanne** [comment]
The release was finally tagged, feel free to update [packaging related information on the wiki](https://github.com/martanne/vis/wiki/Distribution-Packages).

Thanks!

**Comment by mcepl** [comment]
@abaez Is there any hope of “the official” package in the openSUSE:Factory?

**Comment by fgerling** [comment]
There are some `vis` packages in [OBS](https://build.opensuse.org/search?search_text=vis&search_for=0&name=1)
 @mcepl I will try your home repo and check if we can get it into Factory.

**Comment by abaez** [comment]
@mcepl, sorry for the delay on my part. I'll see what I can do to make it into an official package.

**Comment by mcepl** [comment]
The package has been sent to the Factory as https://build.opensuse.org/request/show/779376 . When accepted, it should be the official part of the distribution, available only with ``zypper in vis``.
