### ISSUE TITLE
till with count - next char not counted

### ISSUE THREAD

**Issue by erf** [martanne/vis#499]
Given the following text:
```
This is a line.
```
In `vim` if cursor is at `h` ( just before the first `i` ) and you type `2ti`, cursor moves to just before the second `i`, in `vis` it moves to the last `i` ( i.e. first `i` is not counted ).

UPDATE
This is also the case for `T`

**Comment by lafrenierejm** [comment]
I can second the observation that vis's `t` movement does in fact differ from Vim's `t`.

It seems to me, though, that vis's behavior is preferable.  Vim's help for the till movement states:

> The cursor is placed on the character left of `{char}` inclusive.

 When the cursor is already one character to the left `{char}`, the description provided in Vim's help and the behavior exhibited by `;` would both suggest vis's `t` as the expected behavior.

**Comment by erf** [comment]
Updated the [Wiki](https://github.com/martanne/vis/wiki/Differences-from-Vi(m)) with the difference.
