### ISSUE TITLE
on read, insert file content at cursor pos when in normal mode

### ISSUE THREAD

**Issue by erf** [martanne/vis#503]
When in normal mode and doing a `:r`, i would expect the file content to be inserted at cursor pos.

**Comment by martanne** [comment]
I think the current behavior (inserting on a line below) makes more sense because the file is usually self-contained. It also matches [vim behavior](http://vimdoc.sourceforge.net/htmldoc/insert.html#:read).

What you want can be accomplished using `:< cat filename`. One could probably argue whether the `:r` command is necessary at all.
