### ISSUE TITLE
Difference in cursor movement on Lua API File:insert

### ISSUE THREAD

**Issue by mjwhite** [martanne/vis#510]
This not-very-useful mapping turns `-` into `+` during insertion:

```lua
vis:map(vis.modes.INSERT, "-",
	function(keys)
		vis.win.file:insert(vis.win.cursor.pos, "+")
		vis.win:draw()
	end,
	"Turn minus into plus"
)
```

In a file buffer it works as intended, inserting the `+` and moving the cursor. But in the command buffer, the `+` is inserted to the right of the cursor. To get the intended behaviour there, I need to add

```lua
vis.win.cursor.pos = vis.win.cursor.pos + 1
```

after the `insert` call. I'm not sure which behaviour is expected (possibly the second one?) but I guess both cases should be the same.

**Comment by demonking** [comment]
@mjwhite 
This is the default behaviour.

file:insert is 0 based , but vis.win.cursor.pos starts with 1 at the first position of the file.

http://martanne.github.io/vis/doc/#File:insert

**Comment by martanne** [comment]
The effects you observed are due to an implementation detail of the underlying data structure used for text management.

I tried to [document the provided guarantees](http://martanne.github.io/vis/doc/#Class_Cursor) (not entirely  happy with the description, and yes the link is broken). The short story is that you should update the cursor position after performing the insertions.

However, don't just increment `cursor.pos` as you did above. Instead store the position before the insertion and then calculate the new position based on that (rather than rereading `cursor.pos` again which might be affected by the previous insertion).

```Lua
local data = "+"
local pos = win.cursor.pos
win.file:insert(pos, data)
win.cursor.pos = pos + #data
```


Or just use `vis:insert(data)` which takes care of that and performs the insertion for all cursors.
