### ISSUE TITLE
cw on a single digit changes the following word also

### ISSUE THREAD

**Issue by larryhynes** [martanne/vis#521]
Consider a file containing `one 2 three`. Place the cursor on `2`. `dw` deletes `2`, `cw`deletes `2 three`.

**Comment by martanne** [comment]
Thanks for bringing this up. There are surprisingly many corner cases involved in something as seemingly simple as `cw` and it isn't a priori clear what the desired behavior should be. For example do we want to treat `cw` differently than `dw`?

The current implementation (which contradicts the [information from the wiki](https://github.com/martanne/vis/wiki/Differences-from-Vi(m)#motions-always-behave-the-same-way-irrespective-of-context)) treats `cw` as `ce`. That is why when starting from a single letter word the next word is deleted too.  When starting from a white space symbol (i.e. between two words) the same issue arises.

I think we should first come up with a *comprehensive* list of scenarios (starting cursor position + file content) which can occur, then for each one define what the outcome should be (and whether it is worth implementing). Until now the current implementation was trying to keep it simple by reusing the regular normal mode motions, thus resulting in these (undesireable?) effects in certain "corner cases".

This also seems like a good oportunity for someone who would like to contribute to the project because it is a self-contained task where essentially no prior knowledge is required.  All you have to do is combine some basic primitives (read character, advance to next character, stop) as you would do on an abstract turing machine.

**Comment by larryhynes** [comment]
I stumbled over this in a 'real world' situation, and just now realised that it's not just digits, it's any single character 'word'. (I also now see where you're coming from with regard to *comprehensive*.)

My (admittedly somewhat old-fashioned view) would be to 'do what vi does' in cases such as these, but it's your picnic. I will say that I find it confusing that the behaviour of `dw` and `cw` would be so different; hence, I considered it a bug.

I would say that a word – in this context – can be a single character entity and anything that (mnemonically, at least) operates on 'words' should behave as one might reasonably expect it to, so I would expect `cw` to change the word, not the word and the next word.

**Comment by aeosynth** [comment]
i encountered this, and ended up using `ciw`
