### ISSUE TITLE
switching themes with custom command

### ISSUE THREAD

**Issue by pshevtsov** [martanne/vis#548]
I've ported several color themes for `vis` and now I want to automate screenshots creation. I decided to make a custom command to loop through the list of files in `~/.config/vis/themes directory`, set a theme and run `scrot` to make a screenshot. Here's what I have so far (I'm new to Lua, so that's mostly stackoverflow-driven development):
```lua
vis:command_register("foo", function(argv, force, win, cursor, range)
	for file in io.popen("/usr/bin/find /home/petr/.config/vis/themes -type f"):lines() do
		local name = string.gsub(file, "(.*/)(.*)", "%2")
		theme = string.gsub(name, ".lua$", "")
		vis:command('set theme '..theme)
		os.execute('scrot -d 1 -u /tmp/'..theme..'.png')
	end
end)
```
It creates PNG files but they all are the same, looks like it doesn't switch color themes.

**Comment by martanne** [comment]
As of 49db502f1721184a428feb99ed7621b24ce749bc it should work if you add

```Lua
vis:feedkeys('<vis-redraw>')
```
after the new theme is set. The underlying issue is that we only update the screen once per main loop iteration. While the theme is changed "internally", the changes are not reflected on the screen until your `:foo` command returns.

**Comment by pshevtsov** [comment]
Awesome, thanks!
