### ISSUE TITLE
cannot get "ag -g" output using "<" or "|"

### ISSUE THREAD

**Issue by realwhz** [martanne/vis#556]
`ag` is the binary cmd of The Silver Searcher (https://github.com/ggreer/the_silver_searcher).  It can be used to do both grep like tasks and find like tasks.  Specifically, `ag 'keyword' .` would recursively find all lines of files containing `keyword` from current directory.  `ag -g 'keyword' .` would instead recursively find all files whose names contain 'keyword'.

In vis, if I use the first functionality of ag, namely grep like tasks, it works file.  Both `<` and `|` can get the list.  However, if I do the second kind of tasks, namely using `ag -g 'keyword'` to find files, `<` and `|` will get nothing.  If I use ag in the shell directly, both cmds return lists.

Is there any special requirement to external cmd which can be successfully launched in vis?

**Comment by martanne** [comment]
The problem is not the `-g` flag, but whether you specify an explicit path. The examples you provided using `.` work as expected.

The reason for the observed behavior is that the `<` command implementation uses a pipe to the external application even though there is nothing to write. `ag` detects that it is used in a pipeline (and no arguments were given) and searches in `stdin`, instead of traversing the directory structure.
