### ISSUE TITLE
Enter a command using ":", but backspace out error

### ISSUE THREAD

**Issue by ddkn** [martanne/vis#596]
I have come across a bug, or user idiosyncrasy when trying to enter a command. In **command** mode, I would usually type a command as such:
`:x/myitem`
however, sometimes I may change my mind on a command. One example is I want to search a document in typical vi fashion such as 
`/myitem`
So I start the command such as `:x/myitem`, but then backspace it to `/myitem`. When hitting enter I run into the error
`/myitem`
`Newline expected`
I would expect the parser to be able to handle this change command with no issue. Instead the workaround is to hit **Esc** twice, fairly slowly (with a delay of about 0.5 seconds) or it inserts \<M-Escape\> (which is possibly another user idiosyncrasy?).

The delay issue is noticeable in a few places, when trying to move around quickly, but this is an unrelated concern to this question.

Unrelated note: When I saw the demo video for structural regex in vis, wow! Really cool, and so far really digging this editor!

Using commit 546917d

**Comment by martanne** [comment]
The prompt issue is related to #577. The problem is that there are two different prompts used for searching (`/` and `?`) and commands (`:`). As a short term workaround you can use the sam address `:/myitem` (notice the starting colon). This is not exactly the same as searching because it will create a new selection.

In general (multiline) command entry should be improved. However, it isn't that easy. For example the following is a valid insertion command which can't really be specified right now:

```
:i
Begin
:more text:
End
.
```

See the [FAQ entry](https://github.com/martanne/vis/wiki/FAQ#m-key-is-inserted-whenever-i-press-escape-and-key-in-short-succession) for the Escape delay issue.

**Comment by ddkn** [comment]
Ah, makes sense. I will close this due to being similar to #577. Thanks for the response.
