### ISSUE TITLE
Configuring vis according to documentation causes errors

### ISSUE THREAD

**Issue by benekastah** [martanne/vis#602]
Following the instructions for configuration [here](http://martanne.github.io/vis/man/vis.1.html), I made a config file:

```lua
-- ~/.config/vis/visrc.lua
vis:command('set number')
```
I get the error:

```
Need active window for `:set number'
```

I'm using v0.4

**Comment by joshaw** [comment]
The visrc file is loaded early on in the startup. To change the settings for a window, you need to wait till a window is ready by using the "events" mechanism. 
```
vis.events.subscribe(vis.events.WIN_OPEN, function(win)
	vis:command('set number')
end)
```
That'll run the command each time a new window is opened so that the setting is applied. See the [lua docs](http://martanne.github.io/vis/doc/#Core_Events) for the details

**Comment by martanne** [comment]
In general I agree that the handling of runtime options could be improved, but for now that is how it works.
