### ISSUE TITLE
Inconsistencies in ci... behavior

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#624]
Using `ciw`, the matching word is removed from the view and the editor is placed in insert mode. However, typing `ci<` while in normal mode does not provide any visual indication that the command has been processed and one may begin typing. Only after the first character is typed does the editor update and pressing `<Escape>` results in the loss of the matched content between `<>`, implying that the command did in fact go through.

**Comment by martanne** [comment]
This behaviour is due to the way key handling currently works. The decision whether a given key sequence is a prefix of a mapping is performed on the raw byte level without taking special keys into account.

In this particular case in operator pending mode `i<` is wrongly treated as a possible prefix for `i<Tab>`. Hence the editor waits for further input to distinguish them. If you manually resolve the conflict it should work:
```
:unmap operator-pending i<Tab>
```

In principle it should be possible to adapt the code to take special keys into account.

**Comment by mqudsi** [comment]
I guess the real issue isn't the way the comparison is done but rather that special keys are sent as `<TEXT>` instead of the literal scan code value, but I presume that's an issue with libtermkey/ncurses and not vis?

I'm not clear on why `<Tab>` is the one conflicting and not all special characters in general, but if it is indeed an issue with `<Tab>` only, would replacing `i<Tab>` with `i<C-I>` (given that the tab key in most (all?) terminal emulators sends a `<C-I>` signal) do the trick, then?

**Comment by martanne** [comment]
No, vis deliberately operates on a text representation of the keys and not their scan codes.

If you check operator pending section of the `:help` output you will see that by default `i<` and `i<Tab>` are the only two mappings which start with `i<` thereby causing the conflict. `<Tab>` isn't special here, the problem would also occur with any other special key (including `<C-i>`).

I will shortly push a patch which should hopefully fix the issue (albeit it is only very lightly tested, feedback welcome).
