### ISSUE TITLE
Counts involving 0 are broken if 0's keybind is changed

### ISSUE THREAD

**Issue by beelzebielsk** [martanne/vis#627]
To test this out, you can:

- Open a blank file, making sure that your .visrc file doesn't mess
  with 0's bindings.
- Type in a number.
- Try typing `100<C-a>`. Observe correct behavior.
- Try typing `100<C-x>`. Observe correct behavior.
- Remap 0 to any other command-- *even its current/default command*:
  `map! normal 0 <vis-motion-line-begin>`
- Try typing `100<C-a>`. Observe that instead of an increased count,
  pressing 0 causes the line-begin motion to happen.
- Try typing `100<C-x>`. Observe that instead of an increased count,
  pressing 0 causes the line-begin motion to happen.

This can be done with other commands that accept counts as well, such
as insert. I've personally tried all the commands that I've mentioned, and no other commands.

I'm on ArchLinux, and I'm using the distro package for vis.

**Comment by martanne** [comment]
Not quite sure what you expected to happen?

The default command for `0` is `<vis-count>` which takes care of the issue by [either adjusting the count or performing a motion](https://github.com/martanne/vis/blob/f9cfc764dd501e7ef5517735d797cb5e430545c3/main.c#L1914-L1924) depending on whether we are dealing with a leading zero.

Your new mapping should probably do the same:

```Lua
vis:map(vis.modes.NORMAL, "0", function()
        local count = vis.count 
        if count then
                vis.count = count * 10 
                return 
        end 
        -- do your stuff here 
end)
```

Notice that due to the way input handling and the built-in `<vis-count>` are implemented, it won't work if invoked through an alias. As a result the default behavior can't be restored with:

```
:map! normal 0 <vis-count>
```

**Comment by beelzebielsk** [comment]
I see. I'm coming from Vim, so I'm used to how things work there. Changing the binding for '0' there doesn't break counting; or rather whether or not 0 contributes to a count has nothing to do with it's current binding, as far as I know.

Frankly, the whole idea feels counter-intuitive to me. Why even give a user the option to break all counting which involves the number 0?

Thanks for pointing me to the definition of the count function though. I've been thinking about contributing since I dig the ideas of this editor, and perhaps changing how that part of count works might be a place for me to start.

What I'd do is pretty much what you have there, but instead of hard-coding some default command, just execute whatever 0 is normally bound to.

**Comment by martanne** [comment]
We do not have special privileged internal commands, if you remap something it has immediate effect. In this regard `0` is no different than any other mapping. What makes `0` a bit special is that within the same mode it has a different meaning depending on whether it is used as a count specifier or a motion.

In order to avoid complexity we resolves this ambiguity rather primitively. As a consequence the motion `0` can't actually be used with a count e.g. `1d0` does nothing because it is interpreted as `10d`. (But because the motion `0` is idempotent in vis, i.e. it never crosses line boundaries, it doesn't seem like a severe limitation).

The reason why `<vis-count>` doesn't work when invoked through an alias is that the implementation uses a one character look behind to figure out which digit was entered. In case of the alias this is `>` which doesn't make sense. To fix this we could introduce individual commands `<vis-count-{0,...,9}>`.

**Comment by beelzebielsk** [comment]
Hm. Alright. I took your initial suggestion and rebound 0 using the lua function. It gets the job done. Still doesn't seem quite right, but at least it works. Thanks.
