### ISSUE TITLE
fresh install without visual and / highlight

### ISSUE THREAD

**Issue by valerdi** [martanne/vis#635]
hi there,

i've just install vis to try it out but it seems that i have a problem with highlighting in visual mode and when i search something with /, what should i do?

**Comment by Shugyousha** [comment]
Hi

On Wed, Nov 29, 2017 at 8:12 AM, valerdi <notifications@github.com> wrote:
> i've just install vis to try it out but it seems that i have a problem with
> highlighting in visual mode and when i search something with /, what should
> i do?

First we need to know what the issue is. Is highlighting not working
but the rest ist? Do you get an error? If so, which one?

Then we need to know about software environment you are running vis
in. Which OS are you using? Which version of vis? Did you build vis
yourself or did you download a pre-built library from somewhere?

Only if we have this info we may be able to help you.


Cheers,

Silvan

**Comment by valerdi** [comment]
Hi, the only thing not working is the highlighting of the visual mode and
when i do a search. Everything else is fine, I don't get any error whatsover.

I'm using Ubuntu 16.04 with ZSH. I built vis 0.40-20 by myself with no errors. 
I use kakoune and vim without any problem. 

Thanks.

**Comment by martanne** [comment]
I suspect there is some sort of color theme issue? Which one do you use? What is your `$TERM`? Did you tweak either the theme or your terminal color settings? A screenshot might also help to showcase the issue.

As a side note, the search (assuming you are referring to `/pattern`, as opposed to e.g. `:/pattern`) by default doesn't highlight anything when executed from normal mode.

**Comment by erf** [comment]
@valerdi maybe also see [this](https://github.com/martanne/vis/wiki/FAQ#my-terminal-colors-are-messed-up-what-is-going-on)

**Comment by martanne** [comment]
The problem did only occur for non-Lua builds. I only realized that after @maskedbyte mentioned it in #641.

I'm wondering whether a Github issue template would reduce the amount of guess work required to get reproducible bug reports. Information which might be useful:

* Build configuration: `vis -v`
* Terminal: `echo $TERM`
* OS: `uname -a`
* ... ?
