### ISSUE TITLE
Configure script incorrectly assumes ncursesw is present if termkey is present?

### ISSUE THREAD

**Issue by esdf** [martanne/vis#636]
I was trying to create a homebrew formula for vis0.4 and ran into a problem with the build - If libtermkey is listed as a dependency and installed by homebrew, the vis configure script seems adds the flag `-lncursesw`, which causes the build to fail (because ncursesw is not necessarily present):
```sh
if test -z "$LDFLAGS_TERMKEY"; then
	CFLAGS_TERMKEY=""
	LDFLAGS_TERMKEY="-ltermkey -lncursesw"
fi
```

In order to get the formula working I removed the `-lncursesw` flag from the configure script: https://github.com/Homebrew/homebrew-core/pull/127#issuecomment-348252693
https://github.com/Homebrew/homebrew-core/pull/21215
Is there a better way to solve this?

**Comment by ilovezfs** [comment]
@martanne in case it helps:
```
bash-3.2$ ls -l /usr/lib|grep curses
lrwxr-xr-x   1 root  wheel        20 Nov 11 20:54 libcurses.dylib -> libncurses.5.4.dylib
-rwxr-xr-x   1 root  wheel    519200 Oct 25 09:37 libncurses.5.4.dylib
lrwxr-xr-x   1 root  wheel        20 Nov 11 20:54 libncurses.5.dylib -> libncurses.5.4.dylib
lrwxr-xr-x   1 root  wheel        20 Nov 11 20:54 libncurses.dylib -> libncurses.5.4.dylib
lrwxr-xr-x   1 root  wheel        20 Nov 11 20:54 libtermcap.dylib -> libncurses.5.4.dylib
bash-3.2$ ls -l /usr/include/|grep curses
-rw-r--r--    1 root  wheel    80084 Jul 15 14:02 curses.h
lrwxr-xr-x    1 root  wheel        8 Nov 14 18:31 ncurses.h -> curses.h
-rw-r--r--    1 root  wheel     3898 Jul 15 14:02 ncurses_dll.h
bash-3.2$ 
```

**Comment by martanne** [comment]
I agree it is wrong, apparently it was added in b739323dfd13b177971250ed6f0ce0c58877c0e8. The idea was probably to make it work for builds without curses. Of course as currently written this doesn't make any sense in this scenario either, if anything a dependency for a terminfo library would be needed.

I'm fine with removing it. Having said that, unless someone steps up as a maintainer, macOS will always be treated like a second class citizen. For example the [macOS travis builds currently fail](https://travis-ci.org/martanne/vis/jobs/310530449#L1038) (due to recent infrastructure changes?). I don't really have time right now to track these kind of issues down. It would be nice to get it working again, to have at least basic sanity testing.

**Comment by DomT4** [comment]
> For example the macOS travis builds currently fail 

Should be resolved after https://github.com/Homebrew/homebrew-core/pull/21282 is merged, IIRC.

**Comment by DomT4** [comment]
Disregard the prior comment, looking into it.

**Comment by DomT4** [comment]
Alright, my initial comment was eventually correct 🙄. https://github.com/Homebrew/homebrew-core/pull/21282 should fix at least the `lua` permission issues you're seeing on CI.

**Comment by martanne** [comment]
@DomT4 thanks for looking into it, the [latest builds seem to work again](https://travis-ci.org/martanne/vis/builds/313922140).

@esdf what is the state of the formula? Was this the only issue i.e. does it now work as expected?

**Comment by esdf** [comment]
@martanne The formula was updated to include this patch and now builds fine! It is awaiting feedback/approval.
