### ISSUE TITLE
[security] Crash when parsing special files (e.g. file ACCD)

### ISSUE THREAD

**Issue by mabbamOG** [martanne/vis#679]
**Pull Request**: #680 

I found a crash for this program.
The issue arises due to incorrect parsing of unicode invalid and incomplete bytes in function `view_draw()` (file `view.c`) and leads to a **buffer overflow**.
Luckily, this program is compiled with hardened instructions by default. Which means it is **not exploitable** because `strcat()` is guarded by `__strcat_chk()`.

Here is the code where the overflow occurs:
``` {.C .numberLines startFrom=381}
if (cell.width == 0 && prev_cell.len + cell.len < sizeof(cell.data)) {
    ...
    strcat(prev_cell.data, cell.data);
```

Here is why the overflow occurs:
1. at some point vis reads an invalid unicode sequence and handles it semi-correctly (wrong length, see below).
2. immediatly afterwards vis reads an incomplete  unicode sequence and handles it incorrectly (buffer cursor is reset to position of invalid sequence)
3. the invalid sequence is read again but this time incorrectly accepted and its width is set to zero
4. the `strcat()` code at line 381 is triggered and `prev_cell` contains its previous value plus the invalid byte sequence.
5. go to step 1 -> infinite loop -> overflow at some point with `prev_cell.data` equal to `efbfbdXX...XX` (where `XX` is the invalid sequence and `...` represents its repetition each loop).

and the overflow is due to 3 programming mistakes:
1. data and control information are mixed together when calculating the `.len` value for an invalid unicode sequence.
   This is because invalid sequences are replaced with 3 bytes and yet the `len` is set to 1. 
   This is wrong because `len` is then used for meaningful program execution (such as overflow checks mentioned previously) and declaring a lower number of bytes than is the case may lead to an overflow.
   
   The code where the error occurs:
``` {.C .numberLines startFrom=351}
if (len == (size_t)-1 && errno == EILSEQ) {
			/* ok, we encountered an invalid multibyte sequence,
			 * replace it with the Unicode Replacement Character
			 * (FFFD) and skip until the start of the next utf8 char */
			for (len = 1; rem > len && !ISUTF8(cur[len]); len++);
cell = (Cell){ .data = "\xEF\xBF\xBD", .len = len, .width = 1 };
```
2. data and control information are mixed together when advancing buffer and file position variables.
   In short, the position pointer `pos` for the file is always one character behind the buffer pointer `cur`.

   This happens because the very first `prev_cell` is assigned `.len = 0` and after the first character is read the position for the file is advanced by `prev_cell.len`.
   The code where the error occurs:
``` {.C .numberLines startFrom=387}
pos += prev_cell.len;
prev_cell = cell;
```
3. `mbrtowc()` is not pure and no error checks are made after `wcwidth()` is called.
   After personal analysis, it appears that `mbrtowc()` does not return output solely based on its inputs.
   Here is the issue: if vis encounters an INVALID sequence and then an INCOMPLETE sequence and then the first INVALID sequence again, this leads to the INVALID sequence being accepted in vis. On my machine, I was not able to reproduce this error in a sandbox. I assume it is because `mbrtowc()` is not pure.

   Anyway, even if `mbrtowc()` detects this sequence as valid, the error can still be avoided by checking for `wcwidth()`'s output.
   Since the output is not checked, not only is an incorrect sequence accepted by the program, but it ends up leading to the `strcat()` code mentioned above.

   Here is the code where the error occurs:
``` {.C .numberLines startFrom=369}
		} else {
			if (len >= sizeof(cell.data))
				len = sizeof(cell.data)-1;
			for (size_t i = 0; i < len; i++)
				cell.data[i] = cur[i];
			cell.data[len] = '\0';
			cell.len = len;
			cell.width = wcwidth(wchar);
			if (cell.width == -1)
				cell.width = 1;
}
```

I will soon follow with a proposed "zero-day" patch.
   

## Further Details
I fuzzed this program using vis for a school assignment.
[Attached](https://github.com/martanne/vis/files/1800805/crashes.zip) you will find all files that made vis crash. You can analyze them as follows:
```bash
$ valgrind vis $CRASHFILE 2>&1 | sed 's/\x1b//g'
$ # sed removed escape codes for the terminal
```

Perhaps the best example is the following file (2 bytes): `accd`.

**Comment by mabbamOG** [comment]
I have updated the comment to include the pull request id and the attachments

**Comment by martanne** [comment]
Thanks for the investigation and analysis!

The line where the overflow occurs was just completely bogus. The `cell.len` field has no relation to the length of the NUL terminated display data `cell.data`, instead it refers to the number of bytes of the underlying text represented by this cell. 1c4e0940938373580cf1e3d2184bae8f25259b79 should fix it?

A few comments regarding your analysis (the 3 programming mistakes):

1. This seems correct as is. An arbitrary length invalid multibyte sequence is represented with the Unicode replacement char. (Whether that is useful in practice is a separate issue).
2. The idea is that `pos` is only advanced when a character sequence stored in `prev_cell` is successfully added to the output grid. ae6c3801292c0279a6263ce2b363d0719a0737da takes these processed bytes into account when handling incomplete sequences.
3. It is correct that the conversion state of `mbrtowc(3)` is unspecified after encountering an illegal sequence. This should be fixed in d0efde07da335310b2e9da3bb9a690c2123fbc5e.

The `ACCD` file seems to work now? As does the following:
```
unzip crashes.zip && vis crashes/*
```
although I only checked it briefly and some of the files did not crash in the first place.

Would be nice if you could recheck?

Also we have some [very basic fuzzing infrastructure](https://github.com/martanne/vis-test/tree/master/fuzz) for the core text management data structure in place. If you have automated the process for display related issue that might be useful.

**Comment by mabbamOG** [comment]
I appreciate your taking in consideration this issue and hope I have provided enough information for your review.

----

I'm still uncertain about [1c4e094](https://github.com/martanne/vis/commit/1c4e0940938373580cf1e3d2184bae8f25259b79) and whether it takes care of the vulnerable code, it still looks like a patch:
- what happens if `prev_cell` is overflown with `cell`?
- why is it even necessary to address this situation like this? can this block of code be avoided at a higher level all together?
- `strlen()` takes care of the exploit only partially (for `prev_cell`)

 a more reliable workaround could be to keep `strcat` (which did check for overflows thanks to hardening):
``` C
if (cell.width == 0 && strlen(prev_cell.data) + strlen(cell.data) < sizeof(cell.data)) {
```
this avoids replicating `strcat` with unsafe code (it is not necessary to replace it after all), but it still does not rule out the need for that block of code, and strlen has O(n) complexity so that also makes it an undesirable choice. 

_On a side note: I would like to stress that while it may be a design choice, the `len` variable needs to be completely decoupled from control if it does not represent the real amount of characters within a cell!_

----
As for the comments:
1. The issue is not with design, but with how that design is interlaced with the code. It's fine to keep the Unicode replacement char (it differs from the one denoted in the comments?) but it's not fine to then use that data and pretend it has length 1. Of course, you can fix it by always checking for the size of `data` before using it for some operations (such as with `strlen` before `strcat`).

2. initially my solution to `pos` was similar to [ae6c380](https://github.com/martanne/vis/commit/ae6c3801292c0279a6263ce2b363d0719a0737da) (albeit i was wary to use `len` and used `cur` and other variables instead), but i later realized that if pos was to be kept up to date it made more sense to fix it at the root: when the first character is correctly added to the output grid. Such is the objective of patch #680 and there is no need for special consideration when handling incomplete sequences, as `pos` and `cur` always proceed at the same pace.

3. :+1:  perfect

I would also encourage the developers to take a close look at error 3. The `mbrtowc()` function is a sneaky one and it really would help to reimagine the way it is used. After all, the other bugs are due to error states output by `mbrtowc()`. Maybe using a function for unicode that handles all of that can reduce the attack surface?

---

I can confirm the current state of master is not making my files crash anymore. All the files seem to contain basically a sequence of `invalid byte | incomplete byte` and I believe the `accd`  file to be a sufficient testcase for this issue.

The files were also all making vis crash with the previous master. If they were not all crashing on  your machine, then I would suggest you look into it as there may be differences among systems (I'm running Archlinux x86_64) and this could mean vis behaves differently on various systems..

---

My fuzzing infrastructure was quite simply to use [AFL](http://lcamtuf.coredump.cx/afl/README.txt).
With parallelized fuzzing (AFL doesn't support real concurrency but it does try to make it work) I managed to find the crash after 10 minutes (actually 12 crashes of the same kind!). I fuzzed the program on a single instance on my machine for 10 hours and found 5 crashes of the same kind. If the program is compiled with support for [ASAN](https://github.com/google/sanitizers/wiki/AddressSanitizer) (which is a much faster alternative to Valgrind) then AFL will also find/crash when the program results in clear memory leaks (I don't remember whether you have to tell `afl-gcc` the program was instrumented with ASAN).
It is an excellent fuzzer with genetic traversal of the program (to find all possible paths).
I admit it can be a little slow with programs as vis (I imagine afl kills the program after a while), therefore I would suggest launching vis with a mode (embedded into vis) that simply quits the program after successful opening of a file.

**Comment by martanne** [comment]
Thanks a gain for the report and the test cases!

I hope to address your comments and clarify a few misconceptions about the code:

* "`strcat` is not replaced with unsafe code", the opposite is the case. The new inline loop is bounded by `sizeof cell.data -1` and always NUL terminates `cell.data` thereby fixing the buffer overflow.
* As a result I don't see how `prev_cell` can be overflown with `cell`?
* In general you can have [arbitrarily many combining characters for a single cell](http://archives.miloush.net/michkap/archive/2006/02/17/533929.html). For now we just truncate them when `cell.data` is full i.e. after 15 bytes.
* With the current design `pos` and `cur` can diverge when handling such sequences. The former is only increased when the *complete* sequence was processed, while the latter advances for every combining character. That is probably one reason why #680 doesn't work (as is indicated by the failing test suite on the continuous integration builds: [Linux/macOS](https://travis-ci.org/martanne/vis/builds/352061292), [Windows/Cygwin](https://ci.appveyor.com/project/martanne/vis/build/1.0.383)).
* strlen's O(n) isn't that important for small n (<16 in our case)

I think the issue is fixed, but if you have additional files which cause crashes please share them.

As for the fuzzing, `vis +q filename` is one way to immediately quit after opening the file. I was mainly wondering whether you used additional heuristics (e.g. custom dictionary with invalid Unicode sequences?) to guide the fuzzing or whether it was "stock" AFL.

**Comment by mabbamOG** [comment]
My most sincere apologies! I appear to have misinterpreted a variable and judged that code wrongly.
However, may I suggest a cleaner alternative? This is just to improve semantics for the future:
``` C
if (cell.width == 0) {
    // make sure prev_cell.data is properly NULL terminated!
    strncat(prev_cell.data, cell.data, sizeof(prev_cell.data) - strlen(prev_cell.data) - 1)
...
}
```
this should do the same thing as your code but is easier to understand imo.

Thank you as well for the explanation on `pos`, I had not understood that to be the design for this variable.

As for the fuzzing I used a simple hello world text file and the [UTF8 Sampler](http://kermitproject.org/utf8.html) from the _Kermit Project_ of Columbia University :)
[utf8 sampler.txt](https://github.com/martanne/vis/files/1803199/utf8.sampler.txt)
