### ISSUE TITLE
./configure cannot find liblpeg

### ISSUE THREAD

**Issue by Fre-d-die** [martanne/vis#684]
this could easily be a human error I'm making, I have install lua-lpeg through mac ports yet when attempting ./configure --enable-lpeg-static it say's it cannot find liblpeg, any idea how I can statically link it?

sorry I'm sure I'm missing something simple

**Comment by Two-Finger** [comment]
@Fre-d-die Could you post the absolute path of your LPeg library `.so` file?
And the name of the `.pc` file?

**Comment by Fre-d-die** [comment]
the path to the so is 
>/opt/local/lib/lua/5.3/lpeg.so
not entirely sure what you mean by the .pc file but I could find any .pc file that said "liblpeg.pc" or anything similar, I did however find a lua.pc...

**Comment by Fre-d-die** [comment]
neither of these seemed to work, 
>/opt/local/lib/lua/5.3/lpeg.so 

is now 

>/opt/local/lib/lua/5.3/liblpeg.so

and I have changed the flags, no luck!

**Comment by martanne** [comment]
The `lpeg.so` *shared* object name is fine, but that is the *dynamic* module which will be loaded at runtime by Lua using `dlopen(3)`. See `:help Lua` (in vis) to show the used lookup paths.

If you want to link lpeg statically, then you will need a *static* archive i.e. something along the lines of `liblpeg*.a`. The default makefile as shipped with lpeg does only build the dynamic variant. Hence, it is likely that your mac ports package repository does not provide a static version. See for example this [Alpine Linux patch](https://git.alpinelinux.org/cgit/aports/tree/community/lua-lpeg/build-static-lib.patch) which builds a `lpeg.a`. Once you have such an archive you will have to convince `configure` to actually pick it up. The simplest way is probably to rename the archive to `liblua.a` and place it in one of the standard directories. Otherwise the the previously suggested `LDFLAGS` adjustment might be useful. Also you must make sure that lpeg itself is linked against the same Lua version as vis, otherwise you will experience crashes at runtime.

Is there a particular reason you want to statically link it? I ask because this option has caused some confusion in the past. It is intended for power users/developers who are familiar with these convention and want to produce a portable binary.

**Comment by Fre-d-die** [comment]
if I'm honest the reason I wanted to statically link it is because I couldn't work it out the other way, I used to be a lot more knowledgeable on a lot of super user stuff, but have been away from my laptop and coding for quite a long time, hence reinstalling vis.

**Comment by Fre-d-die** [comment]
another note, when running vis "WARNING: could not find lpeg module" is shown at the bottom of the screen

**Comment by martanne** [comment]
> when running vis "WARNING: could not find lpeg module" is shown

This is because `lpeg.so` is not found in one of the paths listed at the end of the `:help` output. In the `?.so` entries the question mark will be replaced by `lpeg`. Make sure that at least one of the resulting file names exists.

By the way there is now also a [homebrew formula for vis](http://www.braumeister.org/formula/vis) in case you prefer that.

**Comment by Fre-d-die** [comment]
the error has gone now after I have changed the name back to lpeg.so however under the help the file path still reads /opt/local/lib/lua/5.3/?.so is spite of lpeg.so being found in that dir

**Comment by erf** [comment]
I installed `Lua` via `Homebrew` and `Lpeg` via `LuaRocks`.

**Comment by lanodan** [comment]
I have the same error here because lpeg doesn’t provide a pkg-config(``.pc``) file in it’s sources. And I didn’t manage to make a pkg-config and I have no idea where the source for the debian one is.
Also release 0.4 (latest) manages to detect lpeg, so I think there is something to fix in the ``./configure``.

**Comment by Two-Finger** [comment]
@lanodan Try [lua-lpeg-dev](https://packages.debian.org/stretch/i386/lua-lpeg-dev/filelist). That's what I use on Debian. It contains the `.pc` files for [lua-lpeg](https://packages.debian.org/stretch/i386/lua-lpeg/filelist).

**Comment by martanne** [comment]
@Fre-d-die I am not sure what your issue actually is? This might be a case of an [XY problem](http://xyproblem.info/). The `:help` output won't change, it is just that at runtime vis will *internally* replace the `?` with the module name to load.

@lanodan the way I'm reading the [relevant section of the configure script](https://github.com/martanne/vis/blob/85919f6b75fda1f65352b7f97334601ce0c0b4c8/configure#L521), it will still try to fall back to try a few hard coded names, if pkg-config fails. There are some other issues:

 1. pkg-config should probably be invoked with `--static` (thereby making it essentially useless, because nobody ships a static version and adapts their `*.pc` files accordingly). 
 2. It doesn't enforce that the same Lua versions are used i.e. depending on your system state it is possible it would pick up Lua 5.2 but LPeg is linked against 5.3 (or vice versa).
 3. The simple fall back `-l$liblpeg` doesn't enforce/check for static linking either.

but these were all present before the recent changes. Again this configure option is intended for people who have specific needs and are familiar with these kind of things.

@Two-Finger I don't see a static archive in your list either. I'm not sure what the benefit of explicitly  linking it dynamically is. Except maybe that due to our default compile flags it will resolve all symbols at program start (i.e. enforce `BIND_NOW` semantics).

**Comment by Two-Finger** [comment]
@martanne Nice, it works even without linking to liblpeg!
I only did it because I thought it's necessary for the syntax highlighting to work.
Didn't know that Lua would `dlopen(3)` it.

**Comment by Fre-d-die** [comment]
Cheers for the help, works for me now, guess it was just renaming it in the correct path, could have been clearer about the issue, sorry!

**Comment by Two-Finger** [comment]
@martanne I now see that all my changes to this section in `./configure` are probably totally unnecessary.
