### ISSUE TITLE
Prompt history and niceties

### ISSUE THREAD

**Issue by memeplex** [martanne/vis#70]
I feel that vis is pretty usable right now except for the barebones prompt. I know you think these kind of niceties are better implemented outside the editor. Have you considered adding readline support?

**Comment by martanne** [comment]
I agree that the command prompt currently lacks some essential features. I mostly miss history support (i.e. a way to repeat old input) and a way to search for those old inputs (Ctrl-R in readline).

Apart from these, are there other niceties you miss?

For file name completion the current approach [using dmenu or slmenu](https://github.com/martanne/vis/blob/master/vis-open) seems to work fine. The integration could be somewhat improved e.g. by letting <kbd>Tab</kbd> execute the menu with the current prompt content as a prefix pattern.

In general I would like to experiment with a solution in which the editor has no built in prompt at all but instead always launches an external tool like dmenu/slmenu. All entered commands would be saved to a file which would then be used as input for the next invocation. This would give us searchable history support basically for free. The only problem with this is that file name completion would not work as we are already in a menu context and hence can not easily launch a new one showing the directory content.

Another option is to treat the command prompt as a regular file. <kbd>:</kbd> would open this command history file thus showing all past entered commands. This would allow us to use all regular editor features for navigation and editing. <kbd>Enter</kbd> would be remapped to execute the current line as a vis command. <kbd>Tab</kbd> would then launch the file open dialog with the current word as prefix pattern.

So yes the prompt needs to be improved. I plan to refactor the input handling code to allow for run time key bindings which should make it easier to experiment with these ideas. As for the actual use of libreadline: not interested, its source is more than twice the size of the whole editor ...

**Comment by memeplex** [comment]
I think the prompt-as-buffer approach is the saner option. It doesn't introduce yet another mini-edition-language and leverages what the powerful file editor already provides, with a searchable history as a plus.

**Comment by memeplex** [comment]
What about rlwrap on top a very basic prompt? It has rudimentary completion, history and it's probably consistent with what people is already using in the shell and other repls. It could be invoked in vi mode by default.

**Comment by martanne** [comment]
The concept of `rlwrap` is fine: using a standalone tool to enhance existing utilities with line editing and history is a good idea. Unfortunately the actual libreadline implementation sucks, its source is twice the size of vis' C code.

I still think the prompt as buffer approach is interesting. It seems only natural to use the complete editor power to edit the command prompt. The file would store all previous `:commands` <kbd>Enter</kbd> would execute the current line and move it to the start (or end?) of the file. Typing `:` would open this special file, enter insert mode on a new line. Another such file would be used for search terms `/` and `?` prompt. Some care must be taken to handle "recursive" searches. I.e. a search within this special search file would be delegated to `slmenu`. With this execute line/selection mechanism one could also use a special "favorites" file with commonly used commands (bookmarked using special types of marks?) as is often done in Oberon or Acme.

If you prefer recursive listings then change [vis-open](https://github.com/martanne/vis/blob/master/vis-open) to use something based on `find`instead of `ls -1`.

As for the X dependency I agree, this is why `dmenu` is only used as a fallback mechanism.

**Comment by memeplex** [comment]
Indeed I like your approach of opening the scrollback buffer of dvtm using vis or another external editor of choice. Currently I'm using a combo of urxvt perls, vim and readline, each with its own vionic interface. Some level of integration would be very desirable. It's still difficult to introduce the editor into arbitrary repls, ideally the same component will let you edit command prompts, repls and general text (all this without emacs, *ideally*). Btw, I often read complaints about st requiring tmux for scrolling, it's strange that nobody patched it following your dvtm strategy yet. Have you suggested it in suckless list?

**Comment by memeplex** [comment]
I guess you know athame. It unifies the subjects of the two issues I opened here. It's client server and it shows a command line "window" to an underlying vim buffer. The possibility of doing something like this with vis may be taken into account when designing the rpc interface.

PS: you don't like readline bloat and I understand that, but this ardagnir guy wrote such a simple patch and got a binary interface compatible with tons of software almost for free. A cleaner but harder approach would be to keep only the api/abi parts of readline.

**Comment by martanne** [comment]
The latest patches implement my core idea. The `:` command and search `?`,`/` prompts content is kept in two files. The window displaying them have a couple of keys remapped for prompt handling. <kbd>Enter</kbd> will "execute" your command. <kbd>Up</kbd> will enlarge the window so that past entries are visible. The integration is still rough around the edges and can be improved further, but the general concept seems to work.

The changes touched the vis core infrastructure and as such probably introduced a few regressions (for example in my short testing I noticed some strange behavior from the `.` dot command). Unfortunately I won't have much time to work on vis during the next couple of weeks. Nevertheless I wanted to get this out such that interesting people can play with it.

Known issues:
 * Because <kbd>Enter</kbd> is remapped, commands referring to it via aliases such as `o` (open line) will misbehave. Those commands should be changed to use the special key syntax i.e. `<insert-newline>`
 * The default registers are not mirrored. That is changes in the prompt file will overwrite regular register contents.
 * Selected entries are not moved to the end of the file i.e. no most recently used ordering is in place.
