### ISSUE TITLE
vis does not print to stdout

### ISSUE THREAD

**Issue by qstrejo** [martanne/vis#728]
I was trying to hack together a shell script to behave similarly to [ssam](https://github.com/9fans/plan9port/blob/master/bin/ssam). I've tried reading from stdin and writing to stdout with OpenBSD and Linux (v0.5 and the latest git respectively).
``echo "hello" | vis +x/hello/c/bye -``
works, but when quitting with :wq nothing is written to stdout. The manpage seems to explicitly state that this should print to stdout.

**Comment by martanne** [comment]
Hi, the content is in fact written to stdout:
```
echo hello | vis +x/hello/c/bye - > out && cat out
```
However, in normal operation you won't actually see it because upon exiting the terminal state is restored.

I agree that a `ssam(1)` like tool would be handy at times. To do it 'properly' would require some architectural changes. Our rudimentary [test infrastructure](https://github.com/martanne/vis-test) also uses some hacks/plumbing to run vis non-interactively.
