### ISSUE TITLE
Inconsistency between vis and vim ` capitalization

### ISSUE THREAD

**Issue by octos** [martanne/vis#75]
- vim: typing ` toggles the character's capitalization.
- vis: typing ` waits for a command before capitalization.

Is this intended?

**Comment by martanne** [comment]
Are you referring to `~`? In vis it is always implemented as an operator meaning it waits for a motion. This is intentional. The vim behaviour apparently depends on the `{no,}tildeop` setting.

With the fairly new input handling code it might eventually be possible to map `~` to `~l` which would have effect you want? However with the way the key aliases are currently implemented this would cause an infinite loop because the tilde would always be replaced with itself ...

**Comment by octos** [comment]
Yes, sorry: I was indeed referring to `~`. Thank you for your answer. I assume you are in the process of rewriting key aliases. Do you know when the new implementation will be ready?

**Comment by martanne** [comment]
This should now be possible by defining an alias as described in the commit message of 632b5909af96861c881865afae8638a2fd072668. I.e. by adding something like:

    { "~",              ALIAS("<vis-operator-case-swap>l") }
or

    { "~",              ALIAS("<vis-operator-case-swap><cursor-char-next>") }

to your config file.
