### ISSUE TITLE
noremap?

### ISSUE THREAD

**Issue by jocap** [martanne/vis#750]
Hi,

Is there a way to map the following?

    ` -> i
    i -> `

In vim, I believe you'd use `noremap`, but this doesn't seem to exist in vis, which severely limits the capability of the mapping system.

**Comment by ajgrf** [comment]
You can use key actions to swap keys like this:

    map! normal ` <vis-mode-insert>
    map! normal i <vis-nop>

They're all listed in the help output. I'm not sure what you want `i` to do in this scenario, though, after you've swapped it with backtick. Backtick is only bound in operator pending mode, so I assigned the nop action instead of something more useful.

**Comment by martanne** [comment]
While we do not support recursive mappings, the illustrated key actions can often be used to achieve the desired effect.
