### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by XVilka** [martanne/vis#759]
Seems quite a lot of changes already accumulated, plus some PRs pending. I am using vis from git, but would be awesome to update it in various distributions too: https://repology.org/project/vis/versions

**Comment by martanne** [comment]
I plan to do another release fairly soon(tm). While we have basic build testing on [Ubuntu, Windows, macOS](https://github.com/martanne/vis/actions) as well as on [Alpine, Debian, FreeBSD and OpenBSD](https://builds.sr.ht/~martanne/vis), now would be a good time to report any severe issues you have experienced.

Also if anyone is familiar with the Github/Sourcehut integration: it would be nice to have the Github commit statuses include the Sourcehut build outcomes as well. I think it should be possible to setup with a [webhook trigger](https://man.sr.ht/builds.sr.ht/triggers.md#webhook) and dispatch.sr.ht, but I don't have time to investigate right now ...

**Comment by XVilka** [comment]
@martanne yes, it is possible, we did it in radare2:
- https://github.com/radareorg/radare2/commits/master (press any of the commit checks)
- https://github.com/radareorg/radare2/pull/16045#partial-pull-merging ( pull request checks)
- https://github.com/radareorg/radare2/tree/master/.builds (configuration files for FreeBSD and OpenBSD)

**Comment by eworm-de** [comment]
Everything is fine from Arch side. Thanks!

**Comment by ninewise** [comment]
Hm, I'm seeing some trouble on master (30c6ceb2447be5b8b73958271972ba98457dc0b7), getting a 'file already exists' when I open a new file (`vis test`) and `:w` it twice. Just using `:w!` works of course. On Void Linux.

**Comment by eworm-de** [comment]
Please see #814, which should fix the write issue. I hope it does not break anything else.

**Comment by x1ddos** [comment]
> I hope it does not break anything else.

Well, I really hope there's no need for hope. I'd expect code review and automated tests take care of that.

**Comment by martanne** [comment]
The write issue should hopefully be fixed by dc5c1166abc29b6634649eb9872908acdc18c52e.

@eworm-de thanks for looking into it

@ninewise and all others consider to update to latest master and report back whether it works as expected

@x1ddos this area is not well covered by existing tests and there are quite a lot of different combinations: existing and non-existing files, written as `:w` or given as argument `:w some-file`, starting from an unnamed buffer, using different `:set savemethod`s, cases involving symlinks, hardlinks etc.

@XVilka thanks, I didn't realize it could be configured entirely through SourceHut's web interface. I wrongly assumed I had to tweak the build manifest itself. It seems to work now.

**Comment by ninewise** [comment]
Seems fixed. I found no other problems on current master.

**Comment by mcepl** [comment]
No significant problems from openSUSE.

**Comment by martanne** [comment]
Closing, because it finally happened ...
