### ISSUE TITLE
Replace character ambiguity

### ISSUE THREAD

**Issue by anders-dc** [martanne/vis#765]
This issue occurs when I try to replace a single character with a newline from normal mode.

I can obtain the desired result by positioning the cursor and invoking the change operator by pressing `cl<Enter>`. However, if I instead press `r<Enter>`, the character gets replaced by '^M'. This does not appear to be intended.

Both ways work in vi(m). Thanks for vis!

**Comment by Henry-Wilson** [comment]
Seems mostly normal to me. Control+Enter behaves just line Enter for me, so I don't know about that bit (perhaps you mean something other than Control by "cl"), but I do get the same result in replace mode. I think you want to have that happen though, because if I press `^M` (Control+M) on my keyboard it functions as pressing Enter. This seems to be how my terminal is meant to behave, as it is consistent outside of Vis. Are you using an atypical terminal? See if you get the same results that I do when you use `st`.

**Comment by ninewise** [comment]
This is indeed a bug I've encountered as well.

Henry-Wilson: with `cl<Enter>` they meant the letter `c`, the letter `l` and an Enter. You'd `cl<Enter><Esc>` to be the same as `r<Enter>`.

**Comment by Henry-Wilson** [comment]
Okay, I see how `cl<Enter><Esc>` works. There is definitely an inconsistency here between how `Enter` is represented. It seems to always be a newline in insert mode, and the `^M` terminal sequence in replace mode.

**Comment by ninewise** [comment]
Only in single replace, with `R` it's OK.

**Comment by Henry-Wilson** [comment]
Fascinating. This does seem like a bug in the single replace mode. I am now convinced.

**Comment by martanne** [comment]
This is because currently `r{char}` in normal and `<C-v>{char}` in insert mode use the same key translation.  See also 2cfc9c867bdfd4cc3ae3246f31cf636633fe1a5f and #656.
