### ISSUE TITLE
Add visual-block mode CTRL+V

### ISSUE THREAD

**Issue by c99zealot** [martanne/vis#770]

**Comment by ninewise** [comment]
Could you maybe give an example of what you'd use this for? For the things I remember using visual-blocks for, multiple vertically aligned selections on a continuous range of lines are very similar.

**Comment by jcarter777** [comment]
I use visual block a lot for removing areas of whitespace used for alignment, removing sections of a column, capitalising a section of a column - anything regarding selecting columns or multiple partial lines.

![image](https://user-images.githubusercontent.com/47673279/65374067-1d28ac80-dc75-11e9-94e8-1604c327dead.png)

**Comment by ninewise** [comment]
Open the same file in vis, move to the first `A` and run `10<ctrl-j>`. You'll select the same 10 positions as in your screenshot, but each with a different cursor. Removing areas of whitespace used for alignment or sections of a column will be easier then with visual-blocks.

**Comment by theamazingwaffle** [comment]
agree++ on what ninewise said, the cursors thing is the alternative for visual block mode in vim

consider closing the thread

**Comment by Siborgium** [comment]
Multiple cursors feature can do everything visual-block does and more. Agree on closing the thread.

**Comment by geburashka** [comment]
To add to ninewise's comment, after creating the cursors hit `v` to enter visual selection mode to arrive at exactly the same behavior as vim's block mode, ie. `(vim) C-v,jje == (vis) C-j,C-j,ve`.

**Comment by TmpFinger1** [comment]
One thing vis can not do is set the "block" height by applying *any* motion to one of its corners, or by using a textobject. `<C-j>`/`<C-k>` are just hardcoded special cases for the `j` and `k` motions.

Here's a patch that maps `<C-v>` to a new operator capable of creating selections based on the textobject/motion supplied - https://repo.or.cz/vis/gkirilov.git/commit/refs/heads/patch-lastcol-multisel-operator (posted it on the wiki, too)

* it gets applied to all selections, meaning that you can create "multiple blocks"
* when using textobjects, these blocks can have different heights (motions and `<C-j>`/`<C-k>` don't give you that, because they all get the same count argument.

![vblock](https://user-images.githubusercontent.com/56033853/70860565-f30d2080-1f2b-11ea-9538-8556dca89f2d.gif)
