### ISSUE TITLE
Escape from repeating certain actions n times

### ISSUE THREAD

**Issue by theamazingwaffle** [martanne/vis#778]
By repeating certain action n times i mean introducing a number then doing the action binded to the key, example:  
10itext
this would result in texttexttexttexttexttexttexttexttexttext, which is quite convenient.  

However when i accidentally hit a number or mistype the number i need to reset.  
In kakoune it works by hitting escape to cancel repeated actions, example:  
100<esc>itext
will result in just "text" because <esc> cancels the repetition so it will no longer  
do it 100 times, while in vis <esc> will do nothing  

Please make vis behave like kakoune with numbers in normal mode or at least give me a workaround to achieve this behaviour

**Comment by ninewise** [comment]
Using a number just repeats the *next* action. Since backspace is (in normal mode) an alias for `h`, I'd expect `100<Backspace>itext<esc>` to move left 100 characters and insert "text" there (which it does for me).

To replace the 100 previous characters with some "text", you'd write `100chtext<esc>`.

Alternatively, you could rebind backspace in normal mode to `<vis-delete-char-prev>` to have it erase the previous character. Put `vis:map(vis.modes.NORMAL, "<Backspace>", "<vis-delete-char-prev>")` in your visrc.

**Comment by theamazingwaffle** [comment]
Thanks a lot!

Btw, Can i do something like that with escape, but with the whole number, ex 12346<escape> to just cancel the whole number?

**Comment by ninewise** [comment]
Oh I think I understand, now. You could use the snippet below to make backspace in normal mode cancel the pending count. I'd keep escape to remove all but the primary selection though (backspace is pretty useless so it's OK to rebind).

```lua
vis:map(vis.modes.NORMAL, "<Backspace>", function()
	vis.count = nil
end)
```

**Comment by theamazingwaffle** [comment]
Well now thanks a freaking lot!

Finally I can use vis without frustration!

**Comment by TmpFinger1** [comment]
> Can i make escape cancel that number? If i mistyped 112 instead of twelve can i press escape to cancel that number? @theamazingwaffle 

> I'd keep escape to remove all but the primary selection though. @ninewise 

Building upon @ninewise's snippet, here's a mapping that is vim-compatible:

```lua
vis:map(vis.modes.NORMAL, "<Escape>", function()
        if vis.count then
                vis.count = nil
        else
                vis:feedkeys"<vis-selections-remove-all>"
        end
end)
```
