### ISSUE TITLE
libtermkey is EOL

### ISSUE THREAD

**Issue by jvoisin** [martanne/vis#79]
As state on [its website]( http://www.leonerd.org.uk/code/libtermkey/ )

> Note: This project is now DEAD; end-of-life. There will likely be no further releases.

So why is `vis` using it?

**Comment by martanne** [comment]
Because it works and I have _zero_ interest in dealing with the mess that is low level terminal input handling. Besides it consists of only 3 C files which could always be included in vis directly (but I prefer to not do so).

Furthermore there was a [new release](https://github.com/neovim/libtermkey)  10 days ago.
