### ISSUE TITLE
Line is centered automatically after entering commands (undesirable)

### ISSUE THREAD

**Issue by 3dc1d3** [martanne/vis#796]
`zb`, `:set rnu off` results in my line being centered instead of remaining at the bottom - this is jarring and annoying.

What's causing this behaviour?  I assume something to do with drawing the status/message bar?

Edit: additionally when running the above as part of `dvtm-editor` invocation, adding a subsequent `zb` results in being one line above bottom ie. `zb:set rnu off\nzb` in `config.h`.

**Comment by martanne** [comment]
> What's causing this behaviour?

The [primary selection is centered](https://github.com/martanne/vis/blob/30c6ceb2447be5b8b73958271972ba98457dc0b7/view.c#L1138) to give maximal surrounding context. Because of the command window, the `:set` command temporarily moves it off screen causing the re-positioning.

I think the centering generally makes sense. Why is this so undesirable? How often do you use `zb` followed by a `:`-command anyway?

**Comment by 3dc1d3** [comment]
> How often do you use zb followed by a :-command anyway?

Every few minutes, since it was part of my dvtm-editor command.  I've since disabled rnu by default and added a quick toggle bind so don't need that anymore.
