### ISSUE TITLE
vt 100 terminal questions / comments

### ISSUE THREAD

**Issue by erf** [martanne/vis#826]
A few questions / comments regarding vt 100 terminal.

Do order matter? Should `\x1b[H` come before `\x1b[2J` in `ui_vt100_blit`?

Is it enough to call `\x1b[J` ( without 2 ), if you go home first with `[H`.

Should `ui_vt100_clear` clear the screen with
```
output_literal("\x1b[H\x1b[J")
```

Should `ui_vt100_save` save cursor
```
	output_literal("\x1b[s");
```
and `ui_vt100_restore` cursor using
```
	output_literal("\x1b[u");
```

Should `ui_vt100_resize` force a redraw?

Should `ui_vt100_init` save cursor and `ui_vt100_free` do a clear, reset color and restore cursor?

Source to some VT100 commands:
http://www.termsys.demon.co.uk/vtansi.htm

**Comment by martanne** [comment]
Your suggested escape sequence to clear the screen is indeed one byte shorter. I committed it in 348cf46dcbca5fecb342b59144a3ef6b36c3c857.

The `ui_vt100_clear` function can remain a NOP, because the screen is always completely redrawn anyway. It is intended for smarter UI backends which perform partial updates.

Regarding `ui_vt100_resize`, the redraw is forced from the higher level functions.

As for the save/restore/init/free functions: we use the alternate screen buffer (a kind of full screen mode) which has its own associated cursor state. Therefore this should happen implicitly when entering/leaving it. Having said that, the vt100 backend was written in an attempt to get vis running on a minimal OS and wasn't really tested thoroughly.

Did you encounter any concrete problems? If so then feel free to comment/re-open the issue.

**Comment by erf** [comment]
Ok, thanks.

This is not really a problem for me as i usually use the `curses` version which works across terminals, but here are a couple of issues.

I sometimes see a white flash in the lower part of the terminal when scrolling up or down.

The colors are fine in `iTerm2` and `Wezterm` but sometimes looks strange for some themes in the default `Terminal` for macOS.

Here is three themes zipped; `seti`, `st-16` and `sweet-16` with three screenshots, i tok using `Terminal` to demonstrate.

<img width="802" alt="sweet-16" src="https://user-images.githubusercontent.com/1562523/80381685-96d6e780-88a1-11ea-9407-7e4c8278e704.png">

<img width="761" alt="seti" src="https://user-images.githubusercontent.com/1562523/80381604-74dd6500-88a1-11ea-9391-8765bd877967.png">

<img width="810" alt="st-16" src="https://user-images.githubusercontent.com/1562523/80381633-83c41780-88a1-11ea-8901-e47dee1336e8.png">

[themes.zip](https://github.com/martanne/vis/files/4540098/themes.zip)
