### ISSUE TITLE
Display REPLACE mode help

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#83]
```
diff --git a/vis.c b/vis.c
index 26b9fb4..4c5708d 100644
--- a/vis.c
+++ b/vis.c
@@ -2355,7 +2355,7 @@ static bool cmd_help(Filerange *range, enum CmdOpt opt, const char *argv[]) {
 		if (mode->isuser || i == VIS_MODE_TEXTOBJ) {
 			text_printf(txt, text_size(txt), "\n%s\n\n", mode->name);
 			print_mode(mode, txt, i == VIS_MODE_NORMAL ||
-				i == VIS_MODE_INSERT);
+				i == VIS_MODE_INSERT || i == VIS_MODE_REPLACE);
 		}
 	}
 	
```

**Comment by martanne** [comment]
Is this really needed? It will just clutter the help by duplicating the insert mode bindings ...

**Comment by jrdccx** [comment]
* I'm a random following this thread; I practice design (the real kind, not the dribbbler kind) and writing; huge fan of essentials-only, ergo vis *


Assuming the conversation is about usability, not just appeal or tradition:




This could be miles off but, for me, the message at the bottom is the last line of defense when signaling what mode you're in, in any vi: 




It's at the bottom. This requires me to look (far away) from my work to verify my mode; the distracting equivalent of reaching for my arrow keys instead of staying on home row. 




The key is to keep my fingers on home-row and my eyes on my current line. 




Proposed solution: adjust the cursor to reflect the mode:

a) Colors, e.g.,

- Blue COMMAND: Common

- Yellow INSERT: Constructive

- Green/Gray VISUAL: Manipulative

- Red REPLACE: Destructive




- or -




b) Shape:

- Rectangle COMMAND

- Pipe INSERT

- Undscore REPLACE




My personal preference is shape (it requires less parsing than color, less easy to mistake, and is less *distracting*; the color could also be applied to the bar (paired with the cursor shape) as a supplementary environment signal.




IMO (In My *Observation*) understanding what mode you are in is one of the most significant factors in people adopting a vi (the other being understanding key `:commands`).

**Comment by jrdccx** [comment]
Realizing this could come across as throwing in pet feature requests, hers are a few more details (you might already be aware of).


The shapes in particular aren't merely random or convention. They have good metaphorical and mnemonic use:




NORMAL/COMMAND [ ]

A rectangle above  [w]ord   (z index) says: "I'm operating on this text", "I'm traversing across it"




INSERT  |

A pipe between  w|ord  says: "I'm (i)n this text" "I'm inserting" (the  I  shape is a no-brainer)




REPLACE  _

An underscore beneath  w_rd  says: "I'm underneath", "I'm adjusting the foundation, removing the material above"







(Please pardon my earlier grammer burps.)

**Comment by jrdccx** [comment]
"hers are" *shakes head*. I'll wait until I'm at a keyboard to write anything else.

**Comment by TieDyedDevil** [comment]
Re: "Is this really needed?"

Point taken.

Thinking out loud here: Walking up the parent links to list inherited bindings also duplicates information. For example: the basic motion commands appear in multiple listings.

Would it be appropriate to eliminate the "recursive" option altogether and add a separate visualization of the mode hierarchy based upon the actual data structure? One approach would be to annotate the new "Modes" help; another would be to tag each mode header line with the name of its parent mode.

**Comment by martanne** [comment]
Yes I know that there is already duplicated information printed. However exposing the (implementation specific) intermediate modes might be confusing. If we eventually want to support run time key bindings, the current tree based structure of modes will also cause some problems. For example if something is unmapped from a non leaf mode then the mapping would have to be inserted into every child mode. Or the other way around e.g. if we want to allow mappings for insert mode which should not affect replace mode, this is not easily possible.

The tree based mode structure seemed like a good idea in a static setting, but once you allow dynamic modifications, it might not be ideal.

**Comment by martanne** [comment]
@jrdccx your design ideas are interesting, however I don't think they can easily be realized in a terminal environment.

Also notice that vis displays the current mode in the window statusbar not at the bottom of the screen. Hence minimizing the distance (assuming you are using horizontally split windows).

Because vis supports multiple cursors, it does draw its own "cursors" (i.e. changes the cell  fore/background color accordingly) instead of using the one provided by the terminal. Therefore cursor shapes can't really be used (unless your willing to completely hide the content the cursor is currently over). Attributes like underline or italic could be used, but I doubt the effect would be good. 

As for mode dependent cursor colors, they would have to be coordinated with the used syntax colors. This is of course possible, but not completely trivial if we want to support environments with only 16 colors available...

**Comment by jrdccx** [comment]
Internalizing. Can't pretend to understand all of it off the bat; but good topics for personal research.


Meanwhile, here's an example of the cursor shape-shift in vim: https://github.com/jszakmeister/vim-togglecursor




(not implying this by way of a solution, only as an example of implementation).
