### ISSUE TITLE
Weird vis ui behavior

### ISSUE THREAD

**Issue by nemya9066** [martanne/vis#837]
Hi I was messing around with my visrc and the lua api and I noticed that the vis ui start behaving weirdly when I use this command:
vis:map(vis.modes.NORMAL,'gt', function() 
	print('this print message break vis ui')
end )
the message is printed but the ui simply break after that and I start getting weird behavior so can someone please explain to me why vis is behaving this way?
I'm trying to understand how vis work under the hood thank you.

**Comment by martanne** [comment]
Hi, use two terminals and start `vis > log` and `tail -f log`. This redirects your print messages to a file and displays it.

This works because we currently use `stderr` to display the interactive user interface. It also allows usage as a filter i.e.:  `echo Hello | vis - | ...`

As for the reason why it behaves weird: the editor isn't aware of your output and only selectively redraws its UI, hence you end up in an inconsistent state.

Alternatively, you can also use the [Lua API `vis:info()`](https://martanne.github.io/vis/doc/#Vis:info) to display a short message.
