### ISSUE TITLE
Vis for Prose?

### ISSUE THREAD

**Issue by jetrosut** [martanne/vis#932]
Do you think it would make sense and is possible to use Vis for prose? All I need, for example, is soft wrapping, being able to specify a max number of characters to be displayed in a line (setwidth=80), and indenting text on both sides. This could even be made into a plugin or two with [better sentence recognition](https://github.com/reedes/vim-textobj-sentence).

**Comment by mcepl** [comment]
I still believe that neo/vim currently works better for you. `gq` doesn’t exist and the only plugin knowing to me doing something like this ([mine](https://git.sr.ht/~mcepl/vis-par)) is very unfinished and incomplete (patches welcome!).

**Comment by rnpnr** [comment]
I think I will close this now. We have soft word wrapping since 5d7d62c. As for indexing text on both sides, I think that is a job for your terminal emulator. Its really to add via a patch to st for instance.

>`gq` doesn’t exist

I'm not sure what exactly you want from `gq` but `vis:command("map normal gq vip=<Escape>")` has always  done the job for me.

**Comment by mcepl** [comment]
> I'm not sure what exactly you want from gq but vis:command("map normal gq vip=<Escape>") has always done the job for me.

Much more complicated algorithm. E.g., wrapping of [this changelog entry](https://build.opensuse.org/package/view_file/openSUSE:Factory/python311/python311.changes?expand=1), wrapping of emails, etc. I have started [vis-par](https://git.sr.ht/~mcepl/vis-par), but it is suffering from horrible neglect on my side.
